### ISSUE TITLE
type script support

### ISSUE THREAD

**Issue by abadakhshan** [maks/MGit#100]
Hi
Pls add support of type script file in app
Currently i cant view ts files content in app.

**Comment by maks** [comment]
This needs to be done in the CodeMirror-based editor that is shipped within MGit.
PRs are welcome if you would liek to have a go at this, the relevant files are in:
https://github.com/maks/MGit/tree/master/src/main/assets

**Comment by justdave** [comment]
duplicate of #91?

**Comment by abadakhshan** [comment]
Yes
duplicate of #91
When click on ts file external app opened

**Comment by kaeptmblaubaer1000** [comment]
@maks is it a standard CodeMirror, or a modded one?

**Comment by maks** [comment]
It's a stock CM just very old. My plan is to update it and make some fixes but break it out into it's own module and preferably separate app. I think I already have issues here for that work.

**Comment by maks** [comment]
Internal editor is going to be removed: #504
