### ISSUE TITLE
Editing file and then saving (.md) causes random crash

### ISSUE THREAD

**Issue by blamarche** [maks/MGit#102]
When editing a markdown file, saving, then hitting the back button: MGit crashes maybe 50% of the time. The file doesn't appear to be saved when it crashes, despite the message

Just in case: LG L90 and a Moto G, both on CM 13 w/root, Android 6.0.1

**Comment by maks** [comment]
Thanks for logging the issue. I'll try to replicate it here and find whats causing it.

**Comment by maks** [comment]
Also as I mentioned in the Google Play message, a work around would be to use an external editor app for now to let you work with the file. If you save the file in your editor app and then press the back button from your editor app, MGit should automatically update with any changes.

**Comment by blamarche** [comment]
Yep, that functionality seems to work fine. Thanks!

**Comment by maks** [comment]
Internal editor is going to be removed: #504
