### ISSUE TITLE
Unclear "Invalid Remote" toast message on clone failure

### ISSUE THREAD

**Issue by xelxebar** [maks/MGit#106]
## Synopsis

This is more of a request than a bugfix.

Attempting to clone a repository failed with simply an "Invalid Remote" toast message. It took me a long while to diagnose the culprit, but a more verbose message would have likely made me realize my error more quickly.

## Details

The "Invalid Remote" toast was being issued from within the `CloneRepo()` method in `me.sheimi.sgit.repo.tasks.repo.CloneTask` class. In particular, a caught `InvalidRemoteException` from JGit was issuing a toast with simply the `error_invalid_remote` string.

Looking at logcat at the moment that clone fails, the following error from JGit is logged:

    System.err: Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://git@example.com/some-repo.git: fatal: '/some-repo.git' does not appear to be a git repository

I realized that I was simply giving a home-relative path instead of an absolute path.

## Proposal

Since an `InvalidRemoteException` is just a `Throwable`, perhaps the output of `getLocalizedMessage()` could be appened to the toast.

**Comment by maks** [comment]
No, it's definitely a bug and as it happens it's the second report in 24hrs about lack of details in error messages/exceptions.
This will be at least fixed minimally per #105.

**Comment by hakimdiallo** [comment]
Hi, 
I want to contribute on this issue.
Is it related to the #104 one?
Does showing the cause of the error will be fine?
Thanks

**Comment by maks** [comment]
Hi all contributions are most welcome.
As a starting point showing the exception message in a dislodge (no toasts please) would be good, though as per #104 there needs to be a more comprehensive solution of logging full exception stack trace to a file or via email/web api submission.
