### ISSUE TITLE
Can't clone with username or key

### ISSUE THREAD

**Issue by boydkelly** [maks/MGit#115]
Hi,
I had previously used sgit(using public/private keys) , but coming back here I cannot clone a repo that I host with either key or username/password.  When trying to clone I am requested to filll in Remote URL, Local Path, Username and Password. (The name local path seems to me rather ambiguous.)
At best I am prompted for the git user password on my server but it will not authenticate.
I can successfully run git clone git@mydomain.net:gtd on a Linux box and will be prompted for a password.  What is the correct syntax for mgit?

**Comment by gordebak** [comment]
Same here. It always says "authentication not supported". Neither SGit nor Mgit works for me.

**Comment by boydkelly** [comment]
I have uninstalled and reinstalled.  When I go to manage SSH keys I see the directories SSH and sshpub.  However if I select one of those I get a message that it doesn't exist.  When browsing with a file manager there are no directories under com.manichord.mgit.files.  Even the private key file is not there.  Weird.

**Comment by maks** [comment]
@boydkelly sorry for the slow response.
I was able to successfully clone from a private github repo using ssh with a private key **with no password**.
The url syntax is: 
`git@github.com:username/my-repo-name.git`

The "local path" is the folder name that the repo will get **within** the set root folder for MGits repos. This can be changd in MGits settings.

Importing a private ssh key can be done in MGits settings also. Unfortunately the UI is not very good at the moment, what you need to do to select the private ssh key file is press the menu button:

![ic_download](https://cloud.githubusercontent.com/assets/71999/23107585/b8d3ca70-f753-11e6-8dbc-8358c542fa9a.png)

then navigate to the file in your devices fileystem and click on it to select it, If you accidently add an incorrect file, you can remove it from the list of private key files but long pressing on it and then pressing the delete (rubbish bin) menu item.

Unfortunately MGit does not yet support SSH private keys that are password protected but I've bumped that issue to the top of my todo list (#66) as its been so widely requested.

You can also use a username & password with SSH, but in this case you need to include the username in the URL (there is an outstanding issue to fix this also #41) so the syntax you need for that is:
`ssh://username@server.com/path/to/repository`

**Comment by Karmaki** [comment]
Would be nice to copy this answer in the user manual.

**Comment by boydkelly** [comment]
Thank you.  I finally got it with user name and password.   I was also trying to simple copy a a private key to  /data/user/0/com.manichord.mgit/files, but not finding that in my android file system.  Your screenshot made me realize that I have to import the key.  Thanks!  At least im working now with username and password.

**Comment by maks** [comment]
@Karmaki excellent suggestion! I've copy-pasted it (minus typos) into the [FAQ in the wiki](https://github.com/maks/MGit/wiki/faq) 

@boydkelly Great to hear you got it working! Again sorry for the less than great UI/UX, I'll add a new issue to improve that in the future.
