### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#116]
I use mgit every day for development and it crashes often by various reasons. Is it possible to add a report tool like https://github.com/ACRA/acra so I can send a stack trace by email and also read it.
I use it in my app to catch failures:
1. Open default email client 
2. Paste stack trace into a message
3. Set our support email into To.

Then users decide what they would like to do:
1. Read and close email (not send)
2. Hit send.

**Comment by maks** [comment]
Yes agreed. Google Play of course provides crash reports when people choose to allow them to be submitted, but I think the better transparency of what is being submitted via ACRA is much better solution.

**Comment by maks** [comment]
This has been at least minimally implemented in #133
