### ISSUE TITLE
MGit client issues browsing?

### ISSUE THREAD

**Issue by ParzivalWins** [maks/MGit#117]
Is there a way to manage GitHub issues with Mgit client?   Would like to be able to add  labels and control GISTs.  
Thank you.

**Comment by maks** [comment]
MGit is currently a git client, rather than a Github one so no GIthub APIs are being used.
I would suggest for Github-API based functionality such as issues, gists, etc. using a GitHub API app such as the excellent [ForkHub](https://github.com/jonan/ForkHub)
