### ISSUE TITLE
Add root option

### ISSUE THREAD

**Issue by jlppc** [maks/MGit#126]
That would be nice to add a root option to allow cloning repositories in SD card.

**Comment by maks** [comment]
It maybe that you are running into this issue: https://github.com/maks/MGit/issues/101 ?
If not could you please provide some more details on what functionality you need?

**Comment by jlppc** [comment]
I don't have a lot of memory in my phone and I want to clone my git repository in my SD card, but it don't don't work. I imagine that the program needs root or other autorization to do that. Sorry if I made some english errors, I am french.
