### ISSUE TITLE
bug for Chinese

### ISSUE THREAD

**Issue by AoEiuV020** [maks/MGit#129]
version 1.5.0
download from google play,

correct when I use English,

but if I use Chinese as first language,
when I press the menu item "Raw config",
it ask me if I want to delete the repository, "你确定删除这个仓库吗？
other item are the same confusion,

sorry for my poor English,

**Comment by maks** [comment]
This should have been fixed in: 264bffeedee8708951f5f1d6dde6cf2eac14368c
and that fix is in the currently released version (1.5.1) on Google Play.
Please reopen this issue if you find this is still a problem in the current version.
