### ISSUE TITLE
bug?can't diff first commit,

### ISSUE THREAD

**Issue by AoEiuV020** [maks/MGit#132]
when I click the first commit,
it show a toast "diff failed",
I think you can show all added file instead of "diff failed"

**Comment by maks** [comment]
I think this has been very recently fixed in 4f66d52a1e98d5f12a3b31360562aa0cf796eb6f

**Comment by AoEiuV020** [comment]
well,you are right,

2017年3月25日 11:31，"Maksim Lin" <notifications@github.com>写道：
