### ISSUE TITLE
Mgit changes files

### ISSUE THREAD

**Issue by yehudahkay** [maks/MGit#136]
I cloned a repository but mgit is automatically making a change I try resetting but it doesn't help

https://goo.gl/photos/dYkBhciGoNnDEZBQ7

**Comment by kaeptmblaubaer1000** [comment]
@yehudahkay please close, this is a combination of #6 (was fixed) and of #238.

**Comment by yehudahkay** [comment]
Ok, I wasn't able to see how to do a git status in the new version but i'll close as you request

**Comment by kaeptmblaubaer1000** [comment]
@yehudahkay there are three views, if you swipe right or left with the finger you swap them. The last one is Git status.

**Comment by yehudahkay** [comment]
Oh, so the bug is still there

**Comment by kaeptmblaubaer1000** [comment]
@yehudahkay yes, but #6, which changed the file isn't.
If you want to reset the file, long-press the file and select "Checkout".
I'm considering the other half duplicate of #238.

**Comment by yehudahkay** [comment]
I check out a project but in status it says missing files, just like on the original issue i posted.

**Comment by kaeptmblaubaer1000** [comment]
@yehudahkay then long-press the folder with the missing files and use "Checkout":
