### ISSUE TITLE
not usable inside /mnt/extSdCard/ (secondary storage)

### ISSUE THREAD

**Issue by guillaume-d** [maks/MGit#143]
On devices with separate secondary storage (for example `/mnt/extSdCard/` in addition to `/mnt/sdcard/`) `Environment.getExternalStorageDirectory` should not be used (exclusively at least), else only the smaller storage can be used.

In current MGit (and SGit also by the way) it is impossible to import or create a local repository on secondary storage.
Some more actions may also be impossible there (untested), see https://github.com/maks/MGit/search?q=getExternalStorageDirectory to review that.

Possible solutions:
1. add back buttons to all file explorers that could still *default* to the traditional storage directory
1. root all file explorers to `/mnt/` instead? is that portable? or even `/`? (would be confusing for non-experts)
1. make the root directory configurable?
1. devise a smarter solution that could detect what is available?

For more background and ideas see for example http://stackoverflow.com/questions/39462667/titanium-android-external-storage-create-new-directory-and-then-write-files

**Comment by maks** [comment]
I'm sorry but as per #101 it will not be possible to implement this due to restrictions in the Android framework along with the JGit library used in MGit.
