### ISSUE TITLE
Un-Staged/Staged diff causes app to crash.

### ISSUE THREAD

**Issue by TheBeardedB** [maks/MGit#153]
Clicking either of the diff buttons on the status page causes MGit to crash, files can be Staged or Un-Staged and the result is the same. 

In the first image, the PDF exists on the remote already, but the .jar doesn't.
![Files Staged when crash](https://cloud.githubusercontent.com/assets/12553295/25834353/f82ae124-343c-11e7-9d32-89530c9ecde9.png)
In the second image, the .jar does not exist on the remote still.
![File Un-Staged when crash](https://cloud.githubusercontent.com/assets/12553295/25834489/dcaeab28-343d-11e7-8d8c-557a9a08697c.png)

**Comment by maks** [comment]
Thank you for reporting the issue. This looks like its due to MGit not checking for binary files before trying to diff them.

**Comment by maks** [comment]
Actually turns out this was just due to missing null checked from prev code that fixed diff'ing first commit in a repo.
