### ISSUE TITLE
Added Stuff

### ISSUE THREAD

**Issue by SpaceboyRoss01** [maks/MGit#162]
How do I prevent this to show:
```
<<<<<<< HEAD
Version 1.0

=======
Version 0.1.0

>>>>>>> a58ef4530e53e65cbe9efae24ae58fb034d39c3b
```
My git repository is a cloudno.de repository

**Comment by maks** [comment]
I think what you are asking about here is merge conflict markers, which is a standard git feature.
[Please refer to the Git book for more information about this.](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts)
