### ISSUE TITLE
 have an android and I can not compile

### ISSUE THREAD

**Issue by garilla22** [maks/MGit#166]
Can you give me binary static versions?

**Comment by maks** [comment]
Hi, as per the readme, MGit is available on both [Google Play](https://play.google.com/store/apps/details?id=com.manichord.mgit) and [F-Droid](https://f-droid.org/repository/browse/?fdid=com.manichord.mgit)

**Comment by garilla22** [comment]
Giodbuy

**Comment by garilla22** [comment]
Goodbuy
