### ISSUE TITLE
App icon does not display correctly on some devices

### ISSUE THREAD

**Issue by maks** [maks/MGit#176]
Reported via Google Play comments: app icon has a border around it. 
Not clear which devices/android versions are affected.

**Comment by mrvik** [comment]
Android 7.1.1 on Oneplus 5 and Nexus 5 from 6.0.1 to 7.1.2 are affected

**Comment by mrvik** [comment]
![screenshot_20171229-144406_01](https://user-images.githubusercontent.com/18632536/34438422-10585056-eca7-11e7-8249-d2c8a5392f47.jpg)
It looks like this

**Comment by mrvik** [comment]
Yeah, now it has been fixed. Thanks a lot. 
![screenshot_20180424-004613__01](https://user-images.githubusercontent.com/18632536/39157028-2255b494-4759-11e8-869d-19931d73bdfb.jpg)
