### ISSUE TITLE
Tasker Integration Would Be Nice

### ISSUE THREAD

**Issue by ghost** [maks/MGit#179]
I think it would be very useful for some cases to have the possibility to automate steps in Mgit with the help of the popular app Tasker. [Example](https://github.com/orgzly/orgzly-android/issues/8#issuecomment-304738355)

**Comment by IvanMalison** [comment]
@maks @BenKerry Is this not currently possible right now? What would need to be changed to support this? I don't know much about android development, but I'd be willing to help out here.

**Comment by BenKerry** [comment]
I am not a dev but as far as I can tell you don't have to write a whole Tasker plugin. You just have to expose the activity to other apps somehow, so you can run it from tasker. At least the example I linked above works this way.

**Comment by xeor** [comment]
This this idea go anywhere?

**Comment by maks** [comment]
Having a quick look at this, it sounds like what would be needed here is for MGit for example to expose a android service that would allow other apps to for example create a commit on a repo or push/pull a lcoal repos remote.
I don't have time to work on this at the moment, but I'm definitely open to anyone who would like to have a go at submitting a PR to add this to MGit.

**Comment by maks** [comment]
Actually I'll close this in favour of #489 which really covers this and similar use from any other external apps
