### ISSUE TITLE
MGit is Amazing

### ISSUE THREAD

**Issue by ParzivalWins** [maks/MGit#180]
I really appreciate your project. Thank you for creating and supporting. What's the roadmap? Maybe I could help?  
Suggestions. 
--signing commits 
--use Git API to browse repos

**Comment by maks** [comment]
@ParzivalWins thanks! 
Currently the roadmap is basically the issues here, broken up by Milestones, with issues assigned to more distant milestones having a lower priority.
Any help is always **very** welcome.
Please just make sure anything you want to work on has an issue for it here in this repo (you can create one if there is not already one for soemthing you'd like to work on) and then just put a comment in it saying you are working on it. 
Please make sure you create your branch off master here - its always the most current.
Then when you are ready, just submit a PR against master branch of this repo and at the end of the PR description include: `Fixes: #XYZ' where XYZ is the number of the issue the PR addresses.

In regards to 
>Git API to browse repos

I'd prefer for now not to include any use of specific proprietary APIs like Githubs as there are already a number of apps that provide that functionality, though better ways to intergrate with them (eg. registering for github url's in intent-filter) would be welcome, in fact I just created an issue for that: #181

**Comment by maks** [comment]
And I just remembered there is already an issue for signing commits (#94) so that feature would be most welcome too.
