### ISSUE TITLE
Integrate better for commonly used services

### ISSUE THREAD

**Issue by maks** [maks/MGit#181]
It would be helpful for MGit to register intent-filters for commonly used git hosting services urls, both commercial and community (eg. github, bitbucket, google-source etc)

**Comment by Zykino** [comment]
Maybe a "remember my IDs for this domain.tld"
So if I have several repo under gitlab.username.com even if it's not on your famous hosting list it still keep the ID.

Maybe a profile for each domain with the SSH key and login's attached

**Comment by maks** [comment]
@Zykino this issue is about using the Android Intents system to have MGit register to handle Intents for urls for commonly used git hosting services, not around handling user authentication. Please raise a separate new issue if you would like to suggest a new feature around handling user authentication to remote git repos.

**Comment by Zykino** [comment]
Oh sorry, then add a custom address to the list : I want to open git.work.com with MGit as easiely as github. Or school.edu/git/

At least register the git:// scheme.
