### ISSUE TITLE
fix missing translations

### ISSUE THREAD

**Issue by maks** [maks/MGit#192]

**Comment by marukami** [comment]
Something like https://lokalise.co might be able to help manage translations. It's also free for open source.

**Comment by maks** [comment]
@marukami thanks! I have a look at it. My main aim is to make it as easy as possible for contributors (esp non-coding people) to contribute translations.

**Comment by marukami** [comment]
We could set up a Google Form to request access to [lokalise](https://lokalise.co). That might make it simpler for people to register interest.

**Comment by marukami** [comment]
I setup a lokalise project for and uploaded all the strings. Let me know what you think.

**Comment by smichel17** [comment]
There is also weblate.org, which (unlike lokalise) is itself open source.

**Comment by zveber** [comment]
Russian translation still looks quite illiterate. Please  use some service for translation ([weblate.org](https://weblate.org/)  for example).

**Comment by maks** [comment]
@zveber please see my comments in #481 regarding *specifically* what information I need in regards to RU translations, thanks.
