### ISSUE TITLE
ssh cloning broken

### ISSUE THREAD

**Issue by mklier** [maks/MGit#194]
Request to clone or pull a repository via 

ssh://user@site:port/repo

leads to an "Authentication Stop" error. Even the manually provided username/password didn't work.

**Comment by maks** [comment]
Thank you for reporting this. Sorry to be slow responding.

Are you using a private key for your ssh login or just a username/password?
If the latter, then I think you are seeing the same issue as #161.
If that's the case, the work around is to use key based auth for your ssh login (that's the recommended best practise as well)

**Comment by whoo** [comment]
Hi, I've got the same over https connexion.
(No logs/No error | just crash :()
How can I submit more information about that ?

**Comment by maks** [comment]
@whoo Thank you for reporting this.
Could you let me know: 
* which version of MGit you are using and where from (Google Play, F-Droid?)
* the version of android your device is running (found in System Settings->About)
* what operation you were trying to do (clone?) when the crashed happened and if its public, the url of the remote repo?
