### ISSUE TITLE
mgit@manichord.com email account does not exist

### ISSUE THREAD

**Issue by git001** [maks/MGit#198]
Today I have tried to send a crash report from the app.

The app set the recipient address to `mgit@manichord.com`.

I received immediately the following response mail.

```
                  The mail system

<mgit@manichord.com>: host aspmx.l.google.com[74.125.71.26] said: 550-5.1.1 The
    email account that you tried to reach does not exist. Please try 550-5.1.1
    double-checking the recipient's email address for typos or 550-5.1.1
    unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser c29si2155252wrc.110 - gsmtp
    (in reply to RCPT TO command)
```

**Comment by felipe1982** [comment]
I also experienced this yesterday

**Comment by maks** [comment]
Thank you for letting me know and my apologies for that, I had an incorrect setting on my end. That email address should now be working.
