### ISSUE TITLE
Unable to Import as External Repo

### ISSUE THREAD

**Issue by jeffmaner** [maks/MGit#204]
I'm hoping to use MGit for local offline version control of files on my phone.

I have initialized two local repos, both with the same results.

Tapping the + on the main screen, I then tap the Init Local button. I type a path. But there is no Import as external repo checkbox for me to check as mentioned in the User Manual. Tapping the Init button creates the repo. But when I tap on that repo to open it, two alerts pop up, both saying the same thing: Clone failed. No HEAD exists and no explicit starting revision was specified. Tapping OK twice, I then look for a way to add existing files on my phone to the repo, but I see none.

I'm thinking this is a user problem, rather than a bug, but neither the User Manual nor the FAQ addresses my issue.

I'm running the version of MGit I just downloaded today from Play Store on Android 6.0.1 on a BlackBerry PRIV updated 2017 Sept 05. Thanks!

**Comment by maks** [comment]
@jeffmaner sorry about the confusion. Initialising local repos is only possible for "internal" repos, ie. those that are inside the root folder set in MGit's app settings. It is currently not possible to initialise a new empty "external" repo.

**Comment by jeffmaner** [comment]
@maks Thanks for the feedback. If I understand you correctly, I am attempting to initialize a local repo for a folder inside the folder set in MGit's app settings.

I've set the root storage location for repos to `/storage/emulated/0`.

I want `/storage/emulated/0/Documents` to be under version control.

Admittedly, the error I encountered in my original post was due to the fact that, though I thought I had set my root folder, I had actually not. So I was allowed to create a `Documents` repo because `Documents` didn't exist in the default root folder. Once I removed the repos I had created in the default root folder and set the root folder to what I had intended it to be, I was unable to create a local repo `Documents` at `/storage/emulated/0` because the folder `Documents` already exists.

I was able to put my Documents folder on my desktop PC under version control with GitHub Desktop with surprisingly little pain. Am I wrong-headed in expecting to be able to do the same on my phone, or is this capability simply not available yet?

**Comment by maks** [comment]
@jeffmaner thanks for the additional information, yes its a bit confusing that if you don't explicitly set a location for your local repos MGit will default to a non-inituiative one, unfortunately thats the behaviour that was inherited from SGit whicc MGit is a conituation fork of,  so its difficult to change that without impacting a large number of existing users.

With regards to init'ing a new repo when the folder name already exists (but is not a repo), thats **definitely** a bug. I'll track that with this new issue: #205.

The easiest work around for now would be to use a file manager app to rename your existing folder (eg. `Documents-temp`) and then init a new empty repo called `Documents` and then use the file manager app to copy all your existing files from `Documents-temp`->`Documents`. MGit will then detect new files in the repo and allow you to add them as an initial commit.

**Comment by jeffmaner** [comment]
@maks That worked! Great! Thank you so much. I'm looking forward to using this project and watching it mature even further.
