### ISSUE TITLE
External text editor

### ISSUE THREAD

**Issue by merlin-zaraza** [maks/MGit#206]
Add possibility to edit files in external editor

**Comment by maks** [comment]
This is already possible, though unfortunately not very obvious at the moment.
You need to use the "sheet of paper" icon in the toolbar instead of the "pencil" icon when viewing a file within MGit.

**Comment by merlin-zaraza** [comment]
Thank you,

Maybe it's better to use google icon [open-in-app](https://materialdesignicons.com/icon/open-in-app)

**Comment by maks** [comment]
@merlin-zaraza :+1: definitely. Thanks for pointing out that icon, I'll definitely use that.
