### ISSUE TITLE
display gravitar when email filled in for git "profile"

### ISSUE THREAD

**Issue by maks** [maks/MGit#22]
_From @maks on August 4, 2016 6:44_

this will help visually identify for the user they are using the correct git user/email, especially once per-repo user settings are added.

_Copied from original issue: sheimi/SGit#214_

**Comment by Matrixcoffee** [comment]
Please make this very optional. I don't want MGit to connect to any service I didn't tell it to, and worse, feed it potentially private e-mail addresses.

**Comment by Matrixcoffee** [comment]
@kaeptmblaubaer1000 Ah yes, so it is. As for hashing it, unfortunately the search space for e-mail addresses is small enough that it is feasible to build rainbow tables, so the hash can be reversed.

**Comment by maks** [comment]
@Matrixcoffee as pointed out this is an option that can be changed in MGits settings.

**Comment by kaeptmblaubaer1000** [comment]
@maks as your description of this issue point out, you didn't mean that Gravatar can be disabled but rather that the config shows your Gravatar image to your e-mail. To my opinion this is still useful.
