### ISSUE TITLE
No permission for micro sd card causes crash

### ISSUE THREAD

**Issue by fmarkos** [maks/MGit#222]
Does not work when i try to use micro sd

**Comment by robross0606** [comment]
Seeing the same problem on my S8.  It has no permissions for SD card for system.

**Comment by maks** [comment]
I'm sorry but unfortunately there is not really any reasonable way to fix this at the moment as described in #101

**Comment by robross0606** [comment]
Hey, here's an idea.  Add something to the UI to notify people that this is a known problem so they don't bang their heads against a brick wall trying to figure out what's wrong before coming here to post about it.

**Comment by maks** [comment]
@robross0606 very good point! I'm sorry for the hassle this caused.
I've added a new issue to do this #271
