### ISSUE TITLE
Progress display disappears when tilting the device

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [maks/MGit#243]
Also disappears when going to RepoListActivity and reopen the repo.

**Comment by maks** [comment]
Thank you for submitting this issue.
I've actually got a very long outstanding issue (#1) - number 1 infact! to completely redo the way long running operations are handled. 
This is essentially another symptom of the poor existing implementation for long running operations.

As I mentioned in your other issue, unfortunately I've not had time recently to get much work done on MGit, I plan to get back to it soon.
