### ISSUE TITLE
Upload of created directorys on Gitea

### ISSUE THREAD

**Issue by ShalokShalom** [maks/MGit#248]
Hi there :)

1) I create a new directory
2) I commit and upload
3) Gitea shows nothing
4) It works fine from my local Computer

I also tried to commit content into these folders.
Seems like mgit is incompatible with Gitea in this regard?

Android 4.3 on BlackBerry 10
Current version

**Comment by maks** [comment]
I expect this is the same issue as with #249. Given that MGit uses jgit for all git operations and jgit is written and maintained by a git core contributor its likely to be an git implementation bug with whatever gitea uses to implement git. I'm sorry I don't have the time at the moment to look into this further but I'd be happy for anyone else to contribute a fix.

**Comment by ShalokShalom** [comment]
Back and forth: https://github.com/go-gitea/git/issues/109#issuecomment-364630964

**Comment by maks** [comment]
Sorry you're having issues with this.
I think a starting point to tracking down this issue would be to reproduce the issue with another git remote such as here on Github or Bitbucket

**Comment by maks** [comment]
@ShalokShalom could you provide the device and Android version you are seeing this issue on? As it may be related to #259

**Comment by ShalokShalom** [comment]
Already provided

**Comment by maks** [comment]
@ShalokShalom sorry I missed that in your original comment.
In that case, if Gitea is enforcing TLS 1.2 *only* (1.0, 1.1 disabled) as Github have recently started doing then your are almost certainly running into #259. As mentioned there, the workaround for now would be to use SSH instead of HTTPS.

**Comment by ShalokShalom** [comment]
I currently do not use MGit at all, thanks a lot
Since this is a duplicate, will I close this issue, yes?

**Comment by maks** [comment]
No worries, yes I'll close this now.

**Comment by pstrotmann** [comment]
https://github.com/pstrotmann/immoForFree.git: cannot open git-receive-pack
Am I right, that no pushup to Github is possible from now on ?

**Comment by maks** [comment]
@pstrotmann not quite. Currently the situation is that MGit will not work over HTTPS to Github repos on older Android devices that do not support TLSv1.2 as described in #259.
As a work around, you need to use SSH on affected devices until there is a fix for that issue.
Please leave further comments in #259 as this issue is closed.
