### ISSUE TITLE
Cannot open git-receive-pack

### ISSUE THREAD

**Issue by ShalokShalom** [maks/MGit#249]
I get this error when I like to upload something onto 

Https://try.gitea.io/ShalokShalom/start

**Comment by maks** [comment]
I suspect this is a compatibility issue with the git implementation used by gitea.

**Comment by maks** [comment]
duplicate of #248

**Comment by ShalokShalom** [comment]
Seems to be otherwise: https://github.com/go-gitea/git/issues/109#issuecomment-364630964
