### ISSUE TITLE
ability to have different root directory per project

### ISSUE THREAD

**Issue by igormcoelho** [maks/MGit#252]
Dear developers,
I love MGit and it is very useful, but since I'm using several projects interacting with a CPP editor (that works in another directory) I cannot have more than one repository in MGit (otherwise I have to change root directory again).
Is it possible (in the future) to allow full paths (not relative) when cloning a new project?

Thanks a lot and congratulations for the nice product!

**Comment by maks** [comment]
Thank you for the feedback.
It is currently possible to use local repos from locations which are not inside the root directory though the functionality is a bit cumbersome at the moment.
What you need to do is use the "import as external repo" as [described in the manual](https://github.com/maks/MGit/wiki/UserManual#importing-a-local-repo). Given your requirements, be sure to have the  "Import as external repo" box **ticked**.
