### ISSUE TITLE
Wie kann ich einen Ordner pushen ?

### ISSUE THREAD

**Issue by BoBBer446** [maks/MGit#256]
Hallo, ich habe diese tolle App installiert und habe lokal geklont.

Nun würde ich gern den ganzen Ordner pushen - also alles was verändert wurde.
Ich habe jetzt z.b. eine Datei erstellt aber kann sie nicht mit dem repo synchronisieren.

2. Wie kann i h das repo lokal immer aktuell abhalten, wenn jemand anderes am repo Änderungen vornimmt ?

Lg

**Comment by kaeptmblaubaer1000** [comment]
Ich denke, Englisch wäre besser.

**Comment by kaeptmblaubaer1000** [comment]
Just make a commit, and then push.

**Comment by maks** [comment]
Yes do please use english - my german is not great and neither is Google translate.
@kaeptmblaubaer1000 thanks for answering the question, from what I understood of the question thats the correct answer.

**Comment by BoBBer446** [comment]
Yes that solved my problem. Thank you. In the future I write in English :)
