### ISSUE TITLE
For GitHub personal tokens with limited access should be used and stored instead of a password

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#261]
https://github.com/settings/tokens
https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization

**Comment by maks** [comment]
Hi, MGit uses the standard git protocol when communicating with any git remote repo and *not* GitHubs proprietary REST API.

As such you need to use standard Git authentication mechanisms [as documented in the manual](https://github.com/maks/MGit/wiki/UserManual#authentication) and the [FAQ](https://github.com/maks/MGit/wiki/faq#server-authentication)

If you happen to be using 2FA with GitHub, you can use personal token [generated as per Githubs instructions](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
as your HTTPS password in MGIT - this *already* works just fine in MGit.

**Comment by KOLANICH** [comment]
I mean that it may be more secure (in the following sense: when an adversary gained root access (probably on the unused phone, for example stolen), he can extract passwords from the db. Tokens have limited access, so an adversary will not be given global access to the repo like aceess for generating tokens or changing password, and tokens are revokable) not to save password in credentials manager, but, if the host is github, to connect it, check for personal tokens for mgit using API, if there is no create one with limited permissions, and save it instead of password.

**Comment by maks** [comment]
As far as I know tokens are only for use with Github's API and I intend for MGit to remain a standard git client rather than be tied to any one specific service provider.

**Comment by BassMatiOnCode** [comment]
Info

Supplied username and email in the settings. Then I cloned my github repos successfully using the https protocol. Made a change to a file, committed the change, then pushed the changes to github. 

First error message came up, stating that "...no CredentialsProvider is registered". I was a little bit confused, but went on. The following dialog asked for username (or email) and password. If I used my github password, authentication failed. 

I had to create a personal access token first (login to github, then go to https://github.com/settings/tokens, click "generate new token", and follow the instructions. When done, copy the token string to a safe location, it won't be shown again.

If I use this access token as password, everything works fine!

Hope this helps others.
Best regards
Ulrich

**Comment by maks** [comment]
Thanks for leaving your experience to help others @BassMatiOnCode.
I guess the difficult thing for new comers to git is that your email is only used by git for metadata associated with each commit in a git repository, whereas the credentials (eg. access token for github now that they no longer support passwords for http access) are only required for accessing *remote* git repos, eg. Github, Gitlab, Bitbucket etc.

And to finish the explanation, the reason you were able to successfully clone the repo is I would guess that is a public repo, hence anyone can clone it without a login on Github, whereas when you tried to push to it, that of course needs authentication for Github to allow modifying the repo they are storing on your behalf.

I've opened an issue for this: https://github.com/maks/MGit/issues/594
