### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by BoBBer446** [maks/MGit#262]
sorry that i ask. But i want use your app and dont want a other app. 

1. i clone a repo i work with a other one
2. i fetch all data (fetch is mean, that the local files up to date from repo?)
3. i add a file.

But how i can push the the file, new content to dev bunch from repo?
i make a commit and i push but the new file is not see in github dev brunch from the repo.

i know time is short but maybe anyone can help me to work on tablet with this app :)

**Comment by maks** [comment]
Hi.
In MGit its not currently possible to push from any local branch to any remote branch.
What you will need to do is locally in MGit checkout a branch that tracks your remote branch (click on the blue bar at the bottom of the screen in the repo view - initially it will read "master"), make your changes to the branch locally, commit them on your lcoal tracking branch and then push that branch to your remote "dev" branch using the push menu command ("three bars" icon in MGit top rigth hand corner).
Hope that helps.

**Comment by kaeptmblaubaer1000** [comment]
And fetch just downloads the commits. If you also want to update files, use pull.

**Comment by kaeptmblaubaer1000** [comment]
And the current binary version of MGit isn't able to use https://github.com (see #259).
But ssh is still supported (`ssh://git@github.com/<path of repo>`, set up a ssh key in MGit _and_ GitHub).
