### ISSUE TITLE
Files are hidden on Windows

### ISSUE THREAD

**Issue by pungggi** [maks/MGit#267]
Hi, when I connect my android phone with windows I see the folder I setup for my repo, but I do not see any files I could copy to my pc. Any hint?

**Comment by maks** [comment]
Hi could you provide some more details please:
* what path are you using on your device to store the repo?
* are you able to see the files in the repo in MGit?
* are you able to see the files in the repo in a File manager app on your android device?
* what version of android are you using?

**Comment by pungggi** [comment]
Seems that this is not possible.

**Comment by kaeptmblaubaer1000** [comment]
What's not possible?
If you created dotfiles (those beginning with a `.`) then they are generally invisible.
Or maybe the USB connection is unstable (that's why I use an FTP server to transfer files).

**Comment by thebigsmileXD** [comment]
Where are the files located? I can not even find thrm in androids file manager. Root path is storage emulated 0

**Comment by kaeptmblaubaer1000** [comment]
@thebigsmileXD standard is `/sdcard/Android/com.manichord.mgit/files/repo/` (`/sdcard/` is a link to your current `/storage/emulated/` directory, in your case it's the user 0).
But you can change it in the settings.

**Comment by thebigsmileXD** [comment]
Thanks :) @kaeptmblaubaer1000 found it.

When trying to change the storage, the folders are empty.. could it be that this does only work w/ root access?
