### ISSUE TITLE
External editor

### ISSUE THREAD

**Issue by bbruun** [maks/MGit#268]
Would it be possible to add support for an external editor instead of using the built-in version? It isn't very useful for eg markdown editing.

**Comment by polyzen** [comment]
Use the leftmost toolbar button when you have the file open in MGit. The UI for this could certainly be improved on.

**Comment by pjones** [comment]
It would be really neat if there was a way to associate file types with applications so tapping a file would automatically open in the associated app.  If no app is set, MGit should default to its own editor.

I think the included editor is great, but like @bbruun said, for markdown files I'd like to start with a preview before editing the file.

Thank you for all your hard work on MGit.

**Comment by kaeptmblaubaer1000** [comment]
@pjones the idea with Markdown preview is great.
ReStructuredText is also a great candidate for this.

**Comment by maks** [comment]
The internal editor is going: #504
