### ISSUE TITLE
Trouble pulling and now pushing on Samsung Galaxy S4

### ISSUE THREAD

**Issue by ChrisLHall** [maks/MGit#270]
Hello there! I am having trouble pushing to my repository ChrisLHall/MobGameEditor. In order to successfully pull, I had to change my URL to git://github.com/ChrisLHall/MobGameEditor.git. I was unable to clone using https or git@github.com. However, when I try pushing, I get an error that says my url is bad, try using "https://github.com/ChrisLHall/MobGameEditor.git". When I change my remote to point there, I get the error "cannot open git-receive-pack". I tried embedding my username in the https url to no avail.

Any ideas are appreciated! I read online it may have something to do with self signed ssl certs, but I am too nooby to understand what to do about that.

Thanks a lot! By the way, this app is awesome, thanks so much for creating it.

**Comment by maks** [comment]
Thank you for reporting this. Unfortunately you are also running into #259.
The current work around as you have already discovered is to use SSH not HTTPS on affected older android devices.
You will also need to use SSH for pushing to the remote so you should use the same remote (git://github.com/...) to push to *not* a HTTPS one.
The [user manual in the wiki has a section with more information about using SSH with MGit](https://github.com/maks/MGit/wiki/UserManual#ssh)

**Comment by kaeptmblaubaer1000** [comment]
But it's incorrect, `git@github.com:maks/MGit` should be `ssh://git@github.com/maks/MGit.git`.
