### ISSUE TITLE
Algorithm negotiation failed

### ISSUE THREAD

**Issue by KYHSGeekCode** [maks/MGit#294]
When I press push I get this message.

**Comment by maks** [comment]
Could you please let me know which version of Android you are seeing this on, if you are on latest version of MGit (1.5.4.2) and if you installed MGit from Google Play?

**Comment by KYHSGeekCode** [comment]
I am in 4.4.2 android (kitkat) and 1.5.4.2 version mgit, and I got it from
play store. Thanks. Do you need stack trace?

2018년 3월 24일 (토) 오전 11:45, Maksim Lin <notifications@github.com>님이 작성:

**Comment by KYHSGeekCode** [comment]
umm. Stack trace is nonsense. please ignore it.

2018년 3월 26일 (월) 오전 12:19, 걸승빈 <jourhyang123@gmail.com>님이 작성:

**Comment by maks** [comment]
Sorry I should also have asked how are you connecting to your remote git repo via SSH or HTTPS?

**Comment by thejohnha** [comment]
I'm having the same issue. Android 7.1.1 and mgit 1.5.4.2 using ssh.

**Comment by SebastianRiedel** [comment]
Same problem here, Anroid 7.1.1, mgit 1.5.4.2 installed over Google Play Store. Problem occurrs while trying to clone a repository from github.com.

**Comment by kaeptmblaubaer1000** [comment]
@SebastianRiedel try using HTTPS, it has been fixed by me in MGit v1.5.4.

**Comment by RobDWaller** [comment]
I've been suffering from this same issue for a while now also, does version 1.5.4.3 fix this issue and is there a timeline for when that will be available on Google Play store?

**Comment by thejohnha** [comment]
I've been using another app called Forker that works fine:
https://play.google.com/store/apps/details?id=ch.phcoder.jigit&hl=en

**Comment by maks** [comment]
Feel free to use Forker if it works for you but do be aware that its an old fork of the SGit and doesnt appear to be maintained now for a number of years.

**Comment by thejohnha** [comment]
Good point - it looked like a new app, but I just checked the last release date. Ya - Forker's not a good tool to use at least in terms of security - looks like abandonware. I should uninstall it right away. But while MGit is offline - I used it a little.

**Comment by thejohnha** [comment]
Good point - it looked like a new app, but I just checked the last release date and it's 2015. Ya - Forker's not a good tool to use at least in terms of security - looks like abandonware. I should uninstall it right away. But while MGit is offline - I used it a little.

**Comment by maks** [comment]
@thejohnha I'm not sure what you mean by "offline"? MGit is still usable with HTTPS

**Comment by thejohnha** [comment]
Sorry - my bad I just tried with credentials and it works - and even though I had to add the credentials twice (the first time it didn't save them, even though I checked the right box). I previously had an issue where it wouldn't save the credentials so I had to enter them every time, which was a showstopper for me. Maybe it was user error, or maybe that issue got fixed. Thanks! I can use mgit again - but it sure would be nice to have SSH access again. Thank you so much.  :-)

**Comment by maks** [comment]
Glad it works for you now. I think I remember an issue has been logged about HTTPS credentials not always being saved, I'll need to look when I have some time. And yes SSH access is still important, I've flagged this as a priority to work on soon.

**Comment by Nadrieril** [comment]
Same problem here, with mgit 1.5.4.3 from fdroid, via ssh. The server logs say:

> Unable to negotiate with **** port ****: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 [preauth]

This is strange because it used to work a few weeks ago with (AFAIR) the same server configuration. sha1 key-exchange methods have been deemed insecure for a while I believe.

**Comment by KYHSGeekCode** [comment]
I found conditions, using HTTPS is fine but

2018년 3월 26일 (월) 오전 12:29, 걸승빈 <jourhyang123@gmail.com>님이 작성:

**Comment by Nadrieril** [comment]
I think the problem might come from the fact that you use `JSch` version 0.1.5.4 (see https://github.com/maks/MGit/blob/master/dependencies.gradle#L19) instead of the latest 0.1.54 (http://www.jcraft.com/jsch/) due to a typo. The git blame shows that when you created `dependencies.gradle` you changed the version of `jsch` from 0.1.54 to 0.1.5.4.

**Comment by kaeptmblaubaer1000** [comment]
@Nadrieril I think you're right.
I'll create a pull request.

**Comment by Nadrieril** [comment]
I see @kaeptmblaubaer1000's PR has been merged. Is there a way I could get an updated apk to see if that fixes the issue ? I have not been able to build it myself

**Comment by maks** [comment]
@Nadrieril I was planning to get a few more bugfixes in before doing a new release but that should be within the next day or 2 so you won't need to wait long. Also this release will go into the Play Beta channel first so you may want to sign up as a beta user in Play for MGit if you want this release asap.

**Comment by Nadrieril** [comment]
Thanks a lot !
I don't use Google Play. Do you have an idea how long it will take for F-Droid to have this release ?

**Comment by maks** [comment]
@Nadrieril I want to get the next release tagged within the next day or 2. Once thats done its upto F-Droid though I think @kaeptmblaubaer1000 said on MGit Gitter channel it will happen pretty quickly after that.

**Comment by maks** [comment]
FYI the [Gitter channel](https://gitter.im/MGit-Android/Lobby) is available for general discussion like this.

**Comment by kaeptmblaubaer1000** [comment]
@Nadrieril `@relan` enabled Auto-Updates in the F-Droid repository for MGit, so I think a new release should be there in a half day to two days (one day for the bot to find, another day to build)
