### ISSUE TITLE
Adding HTTP proxy support

### ISSUE THREAD

**Issue by kb-1000** [maks/MGit#295]

**Comment by maks** [comment]
Http proxy support? If so, this is already possible and is handled by Android itself.

**Comment by kaeptmblaubaer1000** [comment]
My Android says that the proxy is only for the Browser.
And the git config `http.proxy` may be the solution except for Gravatar.

**Comment by maks** [comment]
Sorry that's not correct. You can set the http proxy for the current Wifi network you are connected to in the advanced settings (for that wifi access point). This settings then applies to all http connections via that wifi AP.
Likewise you can also set a HTTP proxy in the settings for your Mobile data carrier in the Access Points settings.

**Comment by kaeptmblaubaer1000** [comment]
Interesting.
Will try this and then write here.

**Comment by kaeptmblaubaer1000** [comment]
Works, but it's not possible to specify auth.
`http.proxy` should support this, although my desktop Git doesn't...

**Comment by maks** [comment]
Ah yes, good point, lack of proxy auth support is a long standing annoyance on Android.
To add proxy support to JGit for Https within MGit is possible as it uses the basic java HttpURLConnection but not as straight forward as might initially seem. A good starting point is [this SO question](https://stackoverflow.com/questions/34877470/basic-proxy-authentication-for-https-urls-returns-http-1-0-407-proxy-authenticat/34980074?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by maks** [comment]
I'm actually going to close this as really MGit really shouldn't be implementing http proxy functionality.
