### ISSUE TITLE
"Toggle drawer" unneeded

### ISSUE THREAD

**Issue by wildebaard** [maks/MGit#299]
The "toggle drawer" action is not needed: when a user presses the menu button, it is expected the menu is shown - not a another button to show the menu.
This makes a ' add > commit > push' workflow a 9-tap action instead of 6.

**Comment by schumaml** [comment]
+9001 - when I hit this for the first few times, I seriously dreaded that MGit had lost its ability to actually use git to a potential "Pro" version... ;)

**Comment by maks** [comment]
Yes I'll definitely be improving the menu UI shortly

**Comment by kaeptmblaubaer1000** [comment]
I think this is caused by the same change that introduced the bugs v1.5.4.1 and v1.5.4.2 removed: simple appcompat fix in the menu files would be enough. It would be really useful to not have 300+ Android Lint messages... this issue would then have been fixed much earlier.

**Comment by maks** [comment]
@kaeptmblaubaer1000 completely agree. Open end #379 for lint cleanup

**Comment by tanty** [comment]
v1.5.5.1 fro F-Droid here and I still can see this problem.

Using Android 7.1.2 from LineageOS v14.1
