### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [maks/MGit#308]
It currently gives a 404 with `no such key`.

**Comment by kaeptmblaubaer1000** [comment]
@maks please fix this

**Comment by maks** [comment]
Yes, will get this sorted out shortly.

**Comment by maks** [comment]
Finally [done](https://www.manichord.com/projects/mgit.html)

**Comment by kaeptmblaubaer1000** [comment]
Please add a redirect to the `/MGit` and the `/mgit` urls, then this is finally fixed.

**Comment by maks** [comment]
@kaeptmblaubaer1000  sorry I'm not sure I understand why thats necessary?

**Comment by kaeptmblaubaer1000** [comment]
@maks it's because F-Droid and even your repository description are referring to `/MGit`.
And it's better to be case insensitive.

**Comment by maks** [comment]
Play and this repo's description have been updated.
I tried to update F-Droid but for some reason my PR failed to pass their CI and I dont have time to look at that at the moment.
The website is created and hosted statically so creating url alias and redirects is cumbersome.

**Comment by kaeptmblaubaer1000** [comment]
@maks you edited the description of MGit, but it's too long to be on one line.
Their CI checks if their reformatter changes anything, if it does, it fails.

**Comment by kaeptmblaubaer1000** [comment]
@maks I've created https://gitlab.com/fdroid/fdroiddata/merge_requests/3121 to fix this too.

**Comment by maks** [comment]
@kaeptmblaubaer1000 thanks for getting that done on F-Droid!
and yes, I know about meta redirects, but using that would mean adding extra build steps to the way I maintain my site which I'm not keen on atm.
