### ISSUE TITLE
fix resource types

### ISSUE THREAD

**Issue by maks** [maks/MGit#313]
After upgrading to Gradle 3, AAPT2 should be used but cannot due to a number of resources needing to be fixed per [this.](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#aapt2_resource_naming)
Once thats fixed, this: `android.enableAapt2=false`  can be removed from `gradle.properties`

**Comment by kaeptmblaubaer1000** [comment]
I've decompiled MGit v1.5.3 and haven't found the attributes, so it seems like they are just ignored.
