### ISSUE TITLE
Converting Gradle build scripts  to Kotlin

### ISSUE THREAD

**Issue by kb-1000** [maks/MGit#322]
Even Gradle's settings file is already doing so.

**Comment by maks** [comment]
Also need to remove the horrific current use of dependencies.gradle, I have no idea how what I was thinking when I merged that.

**Comment by kaeptmblaubaer1000** [comment]
@maks it's useful when submodules (like the one with `buildSrc` I'm preparing for #321) need to require exactly the same dependency as the root `build.gradle`. This needs to use a separate file, but it's possible to e.g. just using versions from there.

**Comment by kaeptmblaubaer1000** [comment]
@maks you haven't converted build scripts.

**Comment by maks** [comment]
@kaeptmblaubaer1000 sorry which build scripts?

**Comment by kaeptmblaubaer1000** [comment]
@maks I meant the `*.gradle` files.

**Comment by maks** [comment]
reopened as #349 does not do anything to convert from Groovy to Kotlin within the gradle build files themselves.
