### ISSUE TITLE
failed resolution of: Lorg/ietf/jgss/oid

### ISSUE THREAD

**Issue by maks** [maks/MGit#33]
_From @rclasen on July 31, 2016 13:28_

Hi,

when trying to connect to my git repo using ssh I keep getting this error message: "failed resolution of: Lorg/ietf/jgss/oid" (hand-copied - case may vary).

The SSH server is configured to support/offer kerberos/gss authentication - maybe this is related.

Is there a way to workaround this?

thanks,
 Rainer

_Copied from original issue: sheimi/SGit#205_

**Comment by maks** [comment]
_From @gergelypolonkai on September 8, 2016 6:35_

Same here, without Kerberos being involved. Using Android 6.0.1, maybe that matters.

**Comment by kaeptmblaubaer1000** [comment]
@maks is this fixed?

**Comment by maks** [comment]
@kaeptmblaubaer1000 afaik yes, though I do not have any repos that use Kerberos for SSH authentication to verify that.
