### ISSUE TITLE
Can not clone with ssh

### ISSUE THREAD

**Issue by nghiata** [maks/MGit#359]
I clone a response from ssh but it error. "Auth fail" but my username, password is correct.

**Comment by kaeptmblaubaer1000** [comment]
@rawman9x please give more information, e.g. where is the repository stored? If it's here on GitHub, GitHub does only allow password authentication on HTTPS, but not on SSH.

**Comment by rawman9x** [comment]
My repo is restored on cloud server (centos 7) I installed git on my server and I try to clone by mgit client. But it not working.

**Comment by kaeptmblaubaer1000** [comment]
@rawman9x which Git server are you using?
Is an SSH server configured to accept password authenticated connections and does it redirect them to the Git server or SFTP?

**Comment by Numenorian** [comment]
I'm having the same issue described here, attempting password-authenticated clone of a repo over SSH from /srv/git on a raspberry pi on my home LAN. Tried updating to the most recent version available for my Samsung Galaxy S5 and still having the same "auth error." Tried half a dozen times making sure to type in the username & password correctly each time.

Is there any additional information I can provide that would help?

**Comment by ghcme** [comment]
I'm having the same issue. OpenSSH_7.4p1, git version 2.11.0, debian like OS. Official Git clients on different OSs are working properly.

**Comment by KunaPrime** [comment]
i can confim that this problem persists on MGit "1.5.4.6"

**Comment by blackboxgeeks** [comment]
I'm having the same issue trying to clone my repo from my local Ubuntu server running Ubuntu 16.04.4, OpenSSH 7.2, and Git 2.7.  I've install version 1.5.5.1 of MGit from google play.

**Comment by kb-1000** [comment]
Which URL did you use inside MGit? On which port does your server listen?
Which hostname does it have?

>

**Comment by blackboxgeeks** [comment]
In MGit I'm using ssh://myusername@192.168.100.10.2/srv/git/progect.git

the port is 22

**Comment by blackboxgeeks** [comment]
trieded again with the ip and not the host name and it worked this time

**Comment by kb-1000** [comment]
The IP address has a component too many, exactly 4 and not 5 for IPv4

**Comment by maks** [comment]
I'm going to close this now. If there are still any issues around cloning using SSH credentials, please open a new issue, if possible with a publicly accessible repo that reproduces the issue.
