### ISSUE TITLE
DroidEdit is not recognised as file editor.

### ISSUE THREAD

**Issue by PC-RobertD** [maks/MGit#362]
While notepad++ is recognised for some file types, droid isn't.

**Comment by PC-RobertD** [comment]
there is an app called Notepad++ on android devices. I have it installed recently.

**Comment by muojp** [comment]
@PC-RobertD Hi. I tried to reproduce the issue and encountered the situation I cannot recognize the editor you tried.
Searching on Google Play led me to 4 search results below:

Notepad++ for Android https://play.google.com/store/apps/details?id=com.woop.notepad
Notepad++ for Android(R) https://play.google.com/store/apps/details?id=com.rhmsoft.editt
Notepad++ Text Editor https://play.google.com/store/apps/details?id=com.smartappspro.notepad
Notepad ++ para Android https://play.google.com/store/apps/details?id=com.note.pad

It seems they are completely independent from each other. Which one did you try?

**Comment by maks** [comment]
Without any feedback from @PC-RobertD  who opened this issue I'm going to close this now. Feel free to reopen or make a new issue if the specific app in question is identified and still causing problems with MGit
