### ISSUE TITLE
Can't make external file editor a default editor for MGit

### ISSUE THREAD

**Issue by PC-RobertD** [maks/MGit#363]
I'd like to setup DroidEdit as my default editing app

**Comment by kaeptmblaubaer1000** [comment]
@PC-RobertD that's a great idea, but isn't DroidEdit blocked by #362?

**Comment by maks** [comment]
Going to work on this as a priority as I want to remove editor functionality from MGit and instead MGit should work and integrate well with any external editor the user wants to use.

**Comment by maks** [comment]
DroidEdit as default editor works for me with current master, so this will be available in the next release 1.5.7 that will be published shortly.
