### ISSUE TITLE
ExceptionDialog causes crash when it's not called by RepoListActivity

### ISSUE THREAD

**Issue by maks** [maks/MGit#367]

**Comment by kaeptmblaubaer1000** [comment]
@maks I've fixed this in #355

**Comment by maks** [comment]
Thanks yes, I had a look at your commit but that solution is not quite right, we don't really ever want to have "!!"

**Comment by maks** [comment]
@kaeptmblaubaer1000 actually sorry about that! I missed that you are waiting on me for feedback on #355, I'll delete my branch and comment on your PR.

**Comment by kaeptmblaubaer1000** [comment]
@maks okay, I've revised my fix. It uses `SheimiDialogFragment.getRawActivity()` now.
