### ISSUE TITLE
Unable to list local storage files

### ISSUE THREAD

**Issue by phil-flex** [maks/MGit#375]
Import or clone are not able to list local file as sgit do.

**Comment by phil-flex** [comment]
![screenshot_2018-06-24-18-35-52-625_com manichord mgit](https://user-images.githubusercontent.com/34325924/41818280-ebaca296-779a-11e8-9331-0f646ed9ebb9.png)

**Comment by phil-flex** [comment]
Granted it the file storage , solved the issie

**Comment by kaeptmblaubaer1000** [comment]
@phil-flex please reopen this.
It is an issue the developers have to fix.
