### ISSUE TITLE
No log entries in release mode

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [maks/MGit#376]
A `Timber.DebugTree` should be planted anyways to be sure that customers with LogCat access are still able to share the LogCat.

**Comment by maks** [comment]
That's fine, I'm happy to put back std logcat support for Devs who prefer that over using Stetho, see MGitDebugApplication for where to plant debugtree if Stetho is not enabled. There is no point in having a debugtree in non debug builds as it's not possible for users to access an apps logcat on modern versions of android and I don't have time to support users on rooted devices where they would still be able to access it.

**Comment by kaeptmblaubaer1000** [comment]
@maks but sometimes it's useful to get the logcat in an issue you can't reproduce (maybe an API behavior special to a specific device).
How do most developers access the logcat? Using `adb`, but most of them use the UI of AS that uses `adb` or a Java API of it.
It's available even on non-rooted devices.

**Comment by maks** [comment]
@kaeptmblaubaer1000 I think anyone who is capable of installing AS, configuring adb to work on that machine and enabling dev mode on their Android device should be capable of building MGit from src and then using that to get logcat output. 
Its also recommended good practise to disable logcat output on production releases.
I'll re-enable logcat output for debug builds as that makes good sense, but not for production.

**Comment by kaeptmblaubaer1000** [comment]
@maks but I'm unable to install a debug version on my Android device, since a repository list of >100 repos is hard work. Sometimes an issue will only exist on a specific device and Android version. The emulator is unable show this issues, and installing on the main Android device isn't possible since you have to uninstall the app first and this deletes app data.

**Comment by maks** [comment]
@kaeptmblaubaer1000 ok thanks that makes sense but thats a *very* specific use case.
In that specific case, what I think you want to do is use adb backup com.manichord.MGit to backup the app data then do uninstall prod, install debug apk then restore the backup. Note adb backup has options to also backup the apk which of course you don't want for this case.
