### ISSUE TITLE
MGit 1.5.4.5 only shows white branch selector

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [maks/MGit#377]
![device-2018-06-24-141010](https://user-images.githubusercontent.com/18211838/41818939-827b2130-77b8-11e8-838b-17cffc5d72bd.png)
I'm using API level 16.

**Comment by inatz16** [comment]
thank

**Comment by maks** [comment]
yes, having a quick look at this, I think we just need to have textColor attribute for id "commitName" button [sic] in activity_repo_detail_content.xml use a style attribute as already done for its background attribute.
