### ISSUE TITLE
staged/unstaged diff shows only one file out of many

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#382]
![screenshot_20180627-092848](https://user-images.githubusercontent.com/885528/41962522-2c7930e2-79ed-11e8-884a-9caccd57b5f2.png)

![screenshot_20180627-093249](https://user-images.githubusercontent.com/885528/41962532-3264e71c-79ed-11e8-92a3-f33abeea9d52.png)

**Comment by maks** [comment]
Fixed in #380
