### ISSUE TITLE
Unable to clone with public key

### ISSUE THREAD

**Issue by krisko** [maks/MGit#386]
Hi,
I have generated an keypair in the app. Been able to use it with ssh, so it works for sure.
But when I try to clone a repo like ssh://10.10.10.1:2222/home/repos/myrepo.git auth fails and asks for password.

**Comment by kaeptmblaubaer1000** [comment]
@krisko thank you for reporting this.
Please tell me your MGit version and whether your key is password-protected.
Please also check whether you can clone on your standard Git using `ssh://root@10.10.10.1:2222/home/repos/myrepo.git`, since that is what MGit tries without username.

**Comment by krisko** [comment]
Hi,
the version is 1.5.4.5 from fdroid, my key is not passwd protected.
I have a different username for my repos. Also tried to use url ssh://user@IP:PORT/path/to.git but this didn't work either.

**Comment by kaeptmblaubaer1000** [comment]
@krisko can you please give me the logcat messages MGit generates while this issue occurs?
Second question, is it a ed25519 key? They are currently unsupported.

**Comment by krisko** [comment]
It was rsa key generated from the app. 
Anyway, I've tried to remove and install the app again. Generated new keypair and now I'm able to clone the repo. So I cannot to reproduce the issue anymore, sorry. But on the other hand it works now! (: 

Thanks for you time.
