### ISSUE TITLE
.kt file extensions not syntax highlighted

### ISSUE THREAD

**Issue by rahulraopune** [maks/MGit#387]
On opening the source code of .kt kotlin files the text was not syntax highlighted when the file was opened. This can be enhanced as per the pull request #388

**Comment by rahulraopune** [comment]
@kaeptmblaubaer1000  Yes It does work now in my patch

**Comment by rahulraopune** [comment]
I am attaching a screenshot for this what i got on my device.just for confirmation ;)
![screenshot_20180708-140022_mgit](https://user-images.githubusercontent.com/6380808/42418150-0c9b786a-82b8-11e8-870d-0fde57dc7807.jpg)

**Comment by maks** [comment]
Fixed in #388
