### ISSUE TITLE
I would love iOS support as well.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [maks/MGit#389]
For months I wished the iOS git clients had the rebase, cherry-pick and applying of patches made by git format-patch support but None of them supplies that I need or even gpg signing commits as well. In this case I would love if this app could also change that drastically for iOS github devs too. It sucks having to use my mom's Android just to rebase my feature branch off of master whenever I merge to master just to avoid merge commits and force pushing them to github. Especially when not everyone has a laptop or desktop computer or if they got one, a way to hook it up to get power or internet to it.

**Comment by maks** [comment]
I'm sorry but given that MGit is based on JGit which is a java implementation of Git and MGit is currently written as a "native" Android app using Java & Kotlin it is very unlikely that it will ever be ported to iOS.
