### ISSUE TITLE
Cannot checkout non master branches on the remote.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [maks/MGit#390]
Ok, so I noticed that my repository that I cloned using MGit seems to now allow me to checkout my non master branches for some reason. Do you guys mind that upon cloning also checkout all branches from the remote then switch to master and then provide means in the menu to ''Switch to Branch" that switches to a already existing branch though?

Basically I would like to be able to switch from master in my repository to:
- feature branches
- orphan branch icon which contains the repositories readme icon file.
- orphan branch legacy which is a very old version of the source code saved for historical reasons.

Being able to checkout these branches and optionally rebase my feature branches off of changes in master would be great if the branches already exist on GitHub and could possibly have a opened pull request.

**Comment by maks** [comment]
Sorry I'm not sure I follow. You can already checkout any branch locally with MGit.
There is a current bug where unfortunately the control at the bottom of the repo details (commit list) screen is not visible in light mode (#377), but if you switch to dark mode (change to it in MGIt Settings screen) you will be able to see it and use it to check out the branch you need.

**Comment by CatGirlsAreLife** [comment]
Oh I see, also do you plan on adding an import file or photo option too on repositories? It would be nice to have.
