### ISSUE TITLE
Better crash reporting

### ISSUE THREAD

**Issue by maks** [maks/MGit#405]
Using ACRA with email reporting is ok, but having a proper back end would make life easier and also allow better monitoring and require less of end users.
Given FDroids requirement for only oss deps, I'm going to use Appcenter which appears to be the only service with an oss license sdk and a decent backend console.

**Comment by maks** [comment]
Other possible services that have open src android SDKs are bugsnag and sentry.

**Comment by kaeptmblaubaer1000** [comment]
@maks are the servers open source too?

**Comment by Serkan-devel** [comment]
@maks doesn't sentry.io have a hosted option already?

**Comment by maks** [comment]
MGit is using Sentry
