### ISSUE TITLE
Username is Ignored when Logging in via SSH

### ISSUE THREAD

**Issue by maks** [maks/MGit#41]
_From @m1cm1c on September 5, 2016 12:14_

When I try to clone a repository via SSH and want to log in using username and password, I have to use

`ssh://username@server.com/path/to/repository`

If I use

`ssh://server.com/path/to/repository`

and enter the correct username and password, SGit tries to log in using the username `root` (which of course isn't the username I entered into the form).

I think SGit should try to log in using the username the user entered into the form.

_Copied from original issue: sheimi/SGit#253_

**Comment by maks** [comment]
Thank you for taking the time to add the extra details in the issue here, its much easier than on Play store.
At first glance, I think SGit is not passing through the username field when using ssh, only for http.

**Comment by maks** [comment]
_From @m1cm1c on September 5, 2016 12:32_

As a side note: I think before I wrote the bad review (which of course is deleted by now), I also tried `ssh://username@server.com/path/to/repository` a few times and it didn't work. However, I can't seem to be able to replicate it now.

**Comment by maks** [comment]
this in now addressed in the [user manual](https://github.com/maks/MGit/wiki/UserManual#ssh)

**Comment by m1cm1c** [comment]
Wouldn't it be better to just add the given user name to the start of the string? If it's not, people will still be confused and first have to find the corresponding script in the manual. People who don't have administrative access to the server or don't check their server's logs can't even find out that a login of `root` was attempted and therefore will have a hard time gooling the problem.

**Comment by maks** [comment]
Yes that is a good point. 
I expect most people will be copy/pasting in a url from a major provider like here on GH or Bitbucket, so for that case the current UI works best. **But** it would be good for the UI to indicate to the user what will happen if no username is provided within the remote url.
So I'll reopen this issue to improve the UI in that way.
