### ISSUE TITLE
MGit crashes when I try to open my repo

### ISSUE THREAD

**Issue by martinellison** [maks/MGit#420]
When I select the repo it just crashes.

Then It tries for some reason to find a POP/IMAP provider but I do not have one.

**Comment by martinellison** [comment]
I think my repository might have been corrupt (no .git folder?). 

(My objective is to synchronise some app data between my PC and my phone, and my app may have corrupted the repository).

I deleted the whole local repository and recloned it from the server, and now it is working.

But MGit should not crash under these circumstances.

**Comment by kaeptmblaubaer1000** [comment]
@martinellison MGit starts your mail app to send an error report.
You said something about an app, did you use it to copy files to the PC and back?
It may be the case that it removes hidden files (starting with `.`).

**Comment by martinellison** [comment]
My app maybe deleted everything. My issue now is that MGit crashed when it
should just have displayed an error message.
