### ISSUE TITLE
cannot make email dialog go away

### ISSUE THREAD

**Issue by martinellison** [maks/MGit#423]
MGit has crashed and now it keeps asking for an IMAP/POP username and password,  and there appears to be no way to make this go away. So I cannot access my repo now.

**Comment by kaeptmblaubaer1000** [comment]
@martinellison MGit does *not* ask for your email password, your email program does that.
And since you haven't configured it, we can't help you without an error report.
I'll try to write a dummy mail program so that you can post the report here.

**Comment by martinellison** [comment]
Kaeptm,

Understood; actually what I would like is an option to not send an email
report. I do not have email configured on my phone as I use Gmail.

I deleted the local copy of the repository and re-cloned it (as I did not
have any local data that I needed to keep), and it seems to be working at
the moment.

Regards,
Martin

**Comment by maks** [comment]
Sorry you had trouble with this Martin, the current crash reporting is not ideal, I plan to change it soon as I can as per #405
