### ISSUE TITLE
Editor generates NBSP characters

### ISSUE THREAD

**Issue by kb-1000** [maks/MGit#425]
I've only tested this on 8.1 and 4.1.2.
On 4.1.2 it doesn't, but on 8.1 it does.
Maybe it's important that I use Hacker's Keyboard, but I did not change the indentation of a Java line but the line itself.
The whole indentation of that line turned into NBSP (U+00A0).

**Comment by maks** [comment]
Looks like yet another issue with the editor. I think the first step here is just updating to a recent version of Codemirror and seeing what issues just doing that solves: #502

**Comment by maks** [comment]
Internal editor has been removed from MGit.
