### ISSUE TITLE
native git option

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#427]
java git implementation seems to be buggy and slow.
It would be great to be able to choose native git.

I have native git installed using Termix and i must say I have to do more and more in the shell as mgit many times  crashes, locks the index file and has tasks running forever.

**Comment by kaeptmblaubaer1000** [comment]
Termux uses a [patched version of Git](https://github.com/termux/termux-packages/tree/master/packages/git), also it would be needed to completely rewrite the JGit accessing part of MGit (the `tasks` package and the `Repo` class). It would also be much more complicated to extract C Git output.

**Comment by kaeptmblaubaer1000** [comment]
Also, we are just using a very old version of JGit, because of Android API incompatibilities.

**Comment by maks** [comment]
Yes using the git cli is not really an option I want to persue. Using libgit2 is a possiblity, but I am not keen on using a native library and required JNI bindings, but I need to do soem more research and thinking about the best way forward on this.

**Comment by cyberb** [comment]
It ia really painfull to edit multiple projects and push changes, half of the time git is failing.

Unfortunately had to migrate to Termux for git cli and Turbo Editor to edit those files using Android Storage Framework.
Haven't had any git issue since.
