### ISSUE TITLE
Kotlin files in java folder

### ISSUE THREAD

**Issue by BM835** [maks/MGit#436]
Please remove kotlin files from ` Java `
 folder to ` kotlin` folder

**Comment by kaeptmblaubaer1000** [comment]
No, AFAIK this would prevent them from either finding Java files or being found by Java files.

**Comment by maks** [comment]
Yes its pretty standard practise for Android projects that have migrated from Java to Kotlin to continue to keep kotlin src under the `app/java` folder and its not a cause of any issues.
