### ISSUE TITLE
Use crash catch library 

### ISSUE THREAD

**Issue by BM835** [maks/MGit#444]
**How about use crashalytics or any other library to catch crashes**
When you need to do something urgently, and you get an alert with a proposal to send an error report - this is not convenient and very distracting.

**Comment by kaeptmblaubaer1000** [comment]
Well... Crashlytics is not usable in F-Droid (good) and would do not much different.
If you would have looked at the code, it actually catches any unexpected errors and shows them to the user. If you'd like to have the whole app close, and not only the current Activity, feel free to use a patched version of MGit.

**Comment by kaeptmblaubaer1000** [comment]
Would you consider ACRA to be such a library? It is even currently used.

**Comment by BM835** [comment]
@kaeptmblaubaer1000 Yes, I meant, report about crashes without user engagement

**Comment by kaeptmblaubaer1000** [comment]
Well... *without* user engagement... you know that a crash report might contain private information, where you don't expect it? The e mail backend of ACRA has the advantage that the user is able to look at the report before sending it, and do you want your private data to be sent to someone you don't know without prior asking?

**Comment by BM835** [comment]
And how about using crash reports like in Android Studio
Message about errors is shown anywhere, and user can send crash report, that was caught during session
