### ISSUE TITLE
Multiple mistakes in Russian localization

### ISSUE THREAD

**Issue by dmitry-t** [maks/MGit#448]
I'd actually prefer to leave English language, because (almost) nobody translates `commit` and `push`.
* `Удалииь сервер` -> `Удалить сервер`
* `Имя пользователч` -> `Имя пользователя`
* `Ужалить` -> `Удалить` (delete/remove not sting XD)
* `Отправте отзыв` -> `Отправьте отзыв`
* `Слитие` -> `Слияние (merge)`
* `Комитнуть` -> `Зафиксировать (commit)` (yes, with the original command name)

**Comment by kaeptmblaubaer1000** [comment]
Then make a PR for it.

**Comment by dmitry-t** [comment]
This is a really unusual proposal for an ordinary user :)

I can make a PR, but I will not able to build the application and verify it.
So I can accidentally break the build.
Is this acceptable?

**Comment by kaeptmblaubaer1000** [comment]
Yup, that would be acceptable. It would be fixed by someone else then. Just try to not break the XML.

**Comment by mmkhitarian** [comment]
Why is this still unmerged?

**Comment by kb-1000** [comment]
Because *this* is an issue and not a PR.

**Comment by maks** [comment]
My apoliges for not getting to this earlier. As there are at least a couple of Russian-speaker users on this issue, could I get an indication of if people feel its even useful to have a russian translation? as theres been feedback that its actually better for git related text to not be translated.

**Comment by maks** [comment]
I'm going to close this in favour of #481, please yes that issue for my comments and request for feedback on this.
