### ISSUE TITLE
Is SSH impl used in this client secure?

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#454]
When connecting to a server for the first time, ssh usually requires users to manually check the server's fingerprint and then caches the info. 

But I don't remember this client asking me to approve the fingerprint. [Searching on GitHub in this repo by the word "fingerprint" resulted in nothing.](https://github.com/maks/MGit/search?q=fingerprint&unscoped_q=fingerprint)

Is it secure?

**Comment by maks** [comment]
Your search didnt turn up anything because MGit uses the JGit library for all its git operations, which in turn uses JSch library for its ssh functionality, so you would need to look into its source code to answer your question.

**Comment by KOLANICH** [comment]
Fingerprints are usually confirmed manually. I doubt that JGit has Android-specific GUI for it. So I guess if this functionality is present, it has to be in mgit itself.
