### ISSUE TITLE
"Clone failed"

### ISSUE THREAD

**Issue by Joncom** [maks/MGit#457]
When cloning, I get the following:

> Error occurred
> Clone failed

When I click "Send Error Report", then email it generates contains absolutely attachment or text context from which to discern the cause of the error.

**Comment by Joncom** [comment]
It appears that if "ProtonMail" is configured as the default mail client when sending error reports, the text body will not include the usual information dump.

**Comment by Igetin** [comment]
I also get an error when cloning. When trying to send an error report via Gmail or ProtonMail, nothing gets attached to the newly opened draft. Only Outlook worked for me.

**Comment by maks** [comment]
Thank you for reporting this. Email reports via ACRA were only supposed to be a short term thing,

I've now switched MGit over to use Sentry for error reporting in #501 so this should be fixed in the next release.
