### ISSUE TITLE
Repos Not Securely Stored?

### ISSUE THREAD

**Issue by Joncom** [maks/MGit#458]
Is it just me or are repos not stored in a secure location?

It appears that by default, repos are stored in:

Android/data/com.manichord.mgit/files/repos

This means that many other apps can see the repos, and therefore sensitive repos are exposed, right?

**Comment by kb-1000** [comment]
No, they aren't "securely" stored, this has the advantage that you can access them with external editors or file managers or shell environments like Termux. Other apps can't access them though unless you _explicitly_ grant them permission to access your files. Just like with photos made by camera apps.

**Comment by Joncom** [comment]
iOS apps can store app data securely in the app's private folder, so no
other apps can access this data. However, if you want to open that data in
another app (such as a text editor), the source app can pass permission to
read/write that file (and only that file) to the external app, via the iOS
"Files" app.

Basically you say " open this file in an external app" and select the text
editor.

Ie. Only the exact app that needs to access the file gets to.

Is there nothing like this available with android?

**Comment by kb-1000** [comment]
There is something exactly like that, but it is very complicated to implement plus you can't access the repos using shell then anymore. This would be useless on iOS, but is definitely not on Android.

**Comment by Joncom** [comment]
I noticed MGit allows the user to configure where on disk the repos should
be stored. Perhaps allowing optional (and not mandatory) storage in the
private area would allow users to continue using this shell access you
mentioned, while also providing security for repos that need it?

**Comment by maks** [comment]
This is going to change dramatically given the changes happening with storage in Android 10, see #465

**Comment by maks** [comment]
MGit is intended to allow cloning of remote repos so that the local files can be easily accessed by other device-lcoal tools: editors, IDE's, compilers etc, so it is not currently within the design scope to store repos securely on the device. If secure local storage of your git repos is a requirement for you, MGit should not be used.
