### ISSUE TITLE
Open in other apps

### ISSUE THREAD

**Issue by BM835** [maks/MGit#460]
Sometimes, when I need to open file from cloned repository, I need to go to file manager, search directory, and only then open file.

**Comment by kb-1000** [comment]
More details please. If MGit detects the file as text you can already open it in other apps, and otherwise, if it gets the MIME type right (typescript may be detected as video unfortunately) it opens it in external apps otherwise too.

**Comment by BM835** [comment]
For example open ```text/html``` files in browser

**Comment by maks** [comment]
sounds like this needs to be added to the mimetypes that MGit knows about.

**Comment by maks** [comment]
Fixed in #527
