### ISSUE TITLE
Cannot Move Images from Camera Roll into Git Repo

### ISSUE THREAD

**Issue by Joncom** [maks/MGit#461]
There doesn't seem to be any way to move images taken with the camera, into a Git repo...

Many other apps support taking images from the gallery. For example:

- Press and hold an image
- Click "Share"
- Select "Add to Dropbox"

Dropbox (and countless other apps) accept images...

MGit cannot?

**Comment by kb-1000** [comment]
Seriously, you cannot compare MGit to something like Dropbox or Google Drive. MGit accesses real local files that are ordered the same way it seems to be in the UI, those two services at most use an offline cache that will likely be encrypted and not have the same folder structure as in the UI. The only file manager I know that at least older versions of it are capable of this (ES File Explorer) has been removed from Google Play Store. Simply access the repository using your preinstalled Files or Downloads app (on stock ROMs) or get a proper file manager and use them to get them into the repository. It'll be stored in Android/data/com.manichord.mgit/files/repo on your internal storage by default. [maks](https://github.com/maks) should decide whether this will be added

**Comment by Joncom** [comment]
Fine. Maybe a better comparison would be with the "Working Copy" Git client
for iOS. Images can be shared from the camera roll/gallery to various apps,
including the Git client, which then asks, in which repo/folder do you want
to save these selected images. This is really, really simple stuff...

**Comment by kb-1000** [comment]
This isn't a very well comparision either, as on iOS you _can't_ access the files from file managers as far as I know. So it is strictly needed to get such files into the repository. On Android, this isn't the case when storing them in external (= actually internal, there are two mountpoints for data) storage.

**Comment by Joncom** [comment]
iOS does have a file manager/browser called "Files". But anyway, this is
about making the best, easiest, smoothest, Git experience on Android. You
think images should be copied into Git repos another way? Would you mind
detailing that out for me? I'm not aware how to go about doing this in a
way that doesn't feel incredibly slow and cumbersome.

**Comment by maks** [comment]
@Joncom I don't think this is a good use case for using the sharing intent functionality on Android. On Android the share functionality is not intended for this purpose as MGit for instance is not specifically providing any functionality to do with image files and it is *not* a general purpose file store like Dropbox.
MGit does infact register for share intents for uri's that look like git remotes: https://github.com/maks/MGit/blob/master/app/src/main/AndroidManifest.xml#L33
