### ISSUE TITLE
investigate MGit viablility going forward given changes in Android 10

### ISSUE THREAD

**Issue by maks** [maks/MGit#465]
Given the changes that are happening to storage in [Android Q](https://developer.android.com/preview/privacy/scoped-storage) serious thought need to be given on if MGit in its current form will be viable on Q onwards.

**Comment by maks** [comment]
Looks like[ Android 11 is introducing a new API ](https://developer.android.com/preview/behavior-changes-all#all-files-access)to allow for apps like MGit to get access to the whole of storage.

**Comment by martinellison** [comment]
I'm running Android 10 and it seems that I cannot access MGit repositories from other apps. Does everyone on Android 10 have this problem? Where is this going to?

**Comment by maks** [comment]
I think I'll need to look into whether MGit needs to go down the road of requesting "all file" access, as for a lot of situations, having MGit only store local repos in its own app-specific storage would not work well, but I'm happy to get feedback from other MGit users on this.

I should also note that MGit does already support  being a FileProvider, but many other Android apps, eg. text editors don't, thats why I specifically (re)published [ViperEdit](https://play.google.com/store/apps/details?id=com.manichord.viperedit) which does support using File Providers and should work well with MGit.

**Comment by maks** [comment]
For context, now that the current stable verion of MGIt (1.6.2) targets API31, this will begin affecting MGit users running on Android 11 and newer devices.

For Android 11 onwards, the solution would seem to be to use the ["all files" permission](https://developer.android.com/training/data-storage/manage-all-files) and based on Googles docs, MGit probably does fall under the category of apps that Google thinks can be using this permission, ie,
>file manager apps, backup and restore apps, and document management apps

However this does require users to go into their system settings and explicitly grant this permission for MGit. 

I'd be happy to hear feedback from existing MGit users on ANdroid 11 and newer about whether this would be acceptable use or they would rather just use a "well" known location like `Documents`.

**Comment by yuttai** [comment]
Since my local repo root folder is in "/storage/emulated/0/git", if MGit will only access "/storage/emulated/0/Documents" should we migrate our repos ourselves? Like clone all repos to new location again... Or there will be a way to help us migrate? 

About ViperEdit, just want to know whether its a pure text editor or it has some basic IDE functions, like run the edited file in Python or show the HTML in browsers... If it doesn't, we still need to use a python or browser which supports FileProvider to run the file after we edit them...

**Comment by yuttai** [comment]
Besides, I use git to version-controlling not exactly pure text files, like Misrosoft Office and PDF files... I'm not sure whether their editors supports File Provider as well...

**Comment by maks** [comment]
@yuttai thank you for the feedback. Given exactly the points you mentioned, I think I will need to just have MGit usse the "all files" permission.

**Comment by maks** [comment]
Fixed by #616
