### ISSUE TITLE
Suggestion: Date Format

### ISSUE THREAD

**Issue by NeoBeum** [maks/MGit#467]
Just wanted to make a suggestion to be able to customise output format for dates.
Currently the default format is mm/dd/yyyy
![Imgur](http://i.imgur.com/mmq7V5T.jpg)

Option to change from US to UK format would be a nice addition.
Or configurable as dd/mm/yyyy format in any combination.

- YYYY/MM/DD
- YYYY/DD/MM
- DD/MM/YYYY
- MM/DD/YYYY

**Comment by maks** [comment]
I think to start with the format should come from what Locale your device has set.

**Comment by cfoote** [comment]
See pull request #453.

**Comment by maks** [comment]
Now that #453 has been merged and released in version 1.5.3, date format should be per the device Locale.
