### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by dlicse1** [maks/MGit#478]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, a Dialog appears in ViewFileActivity
![2019-08-02 15-19-04_before](https://user-images.githubusercontent.com/53469180/62380708-1077ba00-b54a-11e9-8c90-07a9aded4423.png)
![2019-08-02 15-19-04_after](https://user-images.githubusercontent.com/53469180/62380709-1077ba00-b54a-11e9-875a-01169b0f2f59.png)

2) When I change the orientation of the device screen, UserSettingsActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The Dialog disappears
![2019-08-02 13-30-42_before](https://user-images.githubusercontent.com/53469180/62380507-a6f7ab80-b549-11e9-889c-bf0f70d336fb.png)
![2019-08-02 13-30-42_after](https://user-images.githubusercontent.com/53469180/62380509-a6f7ab80-b549-11e9-9eb0-cd8255a06a00.png)

-- second case --
It loses the scroll position
![2019-08-02 13-26-49_before](https://user-images.githubusercontent.com/53469180/62380510-a7904200-b549-11e9-9353-2182672dabcc.png)
![2019-08-02 13-26-49_after](https://user-images.githubusercontent.com/53469180/62380511-a7904200-b549-11e9-8574-d1036ebe109d.png)

3) When I change the orientation of the device screen, RepoListActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
"Remote URL" EditText loses the focus
![2019-08-02 15-31-52_before](https://user-images.githubusercontent.com/53469180/62379766-e58c6680-b547-11e9-8975-1f7a5304b756.png)
![2019-08-02 15-31-52_after](https://user-images.githubusercontent.com/53469180/62379767-e58c6680-b547-11e9-9f55-81583c28d4b5.png)

-- second case --
"Paste" option disappears
![2019-08-02 14-46-45_before](https://user-images.githubusercontent.com/53469180/62379768-e58c6680-b547-11e9-9859-ed0ed66db12b.png)
![2019-08-02 14-46-45_after](https://user-images.githubusercontent.com/53469180/62379770-e624fd00-b547-11e9-9b48-24a8fa36767d.png)

-- third case --
The Dialog disappears
![2019-08-02 12-51-01_before](https://user-images.githubusercontent.com/53469180/62379771-e624fd00-b547-11e9-9f70-42b9a1ea67e1.png)
![2019-08-02 12-51-01_after](https://user-images.githubusercontent.com/53469180/62379772-e624fd00-b547-11e9-9a27-5987dc93fde0.png)

4) When I change the orientation of the device screen, the Dialog disappears in RepoDetailActivity 
![2019-08-02 12-55-44_before](https://user-images.githubusercontent.com/53469180/62379664-ad852380-b547-11e9-8710-b39c3e9d2dc7.png)
![2019-08-02 12-55-44_after](https://user-images.githubusercontent.com/53469180/62379665-ae1dba00-b547-11e9-8f39-3bc78f293496.png)

5) When I change the orientation of the device screen, PriveteKeyManageActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
It changes the selected directory
![2019-08-02 14-59-54_before](https://user-images.githubusercontent.com/53469180/62379502-5ed78980-b547-11e9-862d-a76cfd7a67c9.png)
![2019-08-02 14-59-54_after](https://user-images.githubusercontent.com/53469180/62379504-5ed78980-b547-11e9-8030-f57eedbd9fc6.png)

-- second case --
It loses the selection
![2019-08-02 14-05-00_before](https://user-images.githubusercontent.com/53469180/62379506-5ed78980-b547-11e9-9a79-c9430543ea94.png)
![2019-08-02 14-05-00_after](https://user-images.githubusercontent.com/53469180/62379507-5ed78980-b547-11e9-821d-2e684c27a480.png)

6) When I change the orientation of the device screen, the Dialog disappears in ImportRepositoryActivity
![2019-08-02 13-36-16_before](https://user-images.githubusercontent.com/53469180/62379417-38b1e980-b547-11e9-8bf7-561a78a25d6d.png)
![2019-08-02 13-36-16_after](https://user-images.githubusercontent.com/53469180/62379418-38b1e980-b547-11e9-8a7f-c7211d218153.png)

7) When I change the orientation of the device screen, ExploreRootDirActivity changes the selected directory 
![2019-08-02 13-30-10_before](https://user-images.githubusercontent.com/53469180/62379365-18822a80-b547-11e9-8e81-f448c535ed4a.png)
![2019-08-02 13-30-10_after](https://user-images.githubusercontent.com/53469180/62379367-18822a80-b547-11e9-91b9-3c00542e3936.png)

8) When I change the orientation of the device screen, ExploreFileActivity changes the selected directory
![2019-08-02 14-05-57_before](https://user-images.githubusercontent.com/53469180/62379285-f092c700-b546-11e9-97a9-57dbd9b49255.png)
![2019-08-02 14-05-57_after](https://user-images.githubusercontent.com/53469180/62379286-f12b5d80-b546-11e9-961e-edef842d29f9.png)

9) When I change the orientation of the device screen, BranchChooserActivity loses the selection
![2019-08-02 13-10-23_before](https://user-images.githubusercontent.com/53469180/62379207-ca6d2700-b546-11e9-9adc-e915de69f232.png)
![2019-08-02 13-10-23_after](https://user-images.githubusercontent.com/53469180/62379208-cb05bd80-b546-11e9-92b8-0d7d372cb35a.png)

**Comment by maks** [comment]
TRhank you for taking the time to test the apps screen rotation handling, but these are at best minor annoyances, if you have found any serious bugs while using the app, please feel free to file new issues.
