### ISSUE TITLE
cannot open git-upload-pack

### ISSUE THREAD

**Issue by maks** [maks/MGit#48]
_From @ckp5566 on October 17, 2016 3:31_

Hi 
I try to use "http" to git clone my git on my own server
but there is an error "org.eclipse.jgit.api.errors.TransportException : cannot open git-upload-pack"
the link "http://user:password@ip:port/gitdata"  works well on my computer, but when I use this link on sgit on my android device, it gets an exception of "cannot open git-upload-pack".

Any one know what's happen of this?

_Copied from original issue: sheimi/SGit#277_

**Comment by maks** [comment]
Instead of putting the username and password into the URL, please enter them instead into the relevant field in the clone dialogue in SGit.

**Comment by maks** [comment]
_From @ckp5566 on October 18, 2016 6:48_

Enter user/password at dialogue  will get the same error

**Comment by maks** [comment]
@ckp5566 If possible, could you please provide a url to a publicly accessible repo where this is occurring?

**Comment by guest73** [comment]
Yep, I have exactly the same problem.

**Comment by maks** [comment]
@guest73 If possible, could you please provide a url to a publicly accessible repo where this is occurring?

**Comment by guest73** [comment]
But I guess It might be related to this https://stackoverflow.com/a/25917888.

**Comment by maks** [comment]
@guest73 that might be the case if you are connecting via Https and the server has a self-signed cert. 
If so you can work around this by adding the servers SSL cert to your android devices keystore.

**Comment by Wryhder** [comment]
@maks I have this same issue. I'm unable to clone or pull or push. Nothing. I installed the app and used it fine for like two days. I cloned, pulled, pushed to github fine. And then I was getting this 'cannot open git-upload-pack' error. Should I open a separate issue for this? The error message is the same, after all.

I attempted to fix by doing an uninstall then reinstalling. Major mistake, as now I can't clone those repos I already had. Even if I downloaded and added them manually, I still can't pull or push changes.

**Comment by maks** [comment]
@Wryhder I suspect you are on an older version of Android too then?
If so then in fact you are seeing the same issue reported in #260
I'll post further information there.

**Comment by gitox** [comment]
I added -Dhttps.protocols=TLSv1.1,TLSv1.2 to eclipse.ini and it solve the problem.

**Comment by gacloudy** [comment]
I was just in the same problem. But I  added  -Dhttps.protocols=TLSv1.1,TLSv1.2 to eclipse.ini  and this problem was solved like gitox did.

**Comment by maks** [comment]
Please do not keep posting here about adding that setting to eclipse.ini as it is completely irrelevant and not helpful to MGit users.

**Comment by gummikalli** [comment]
I had this issue in Eclipse, had to push using Git Bash. I changed push origin from https to ssh and everything works fine.

**Comment by Cligor** [comment]
@gitox thanks! This solve my problem.
