### ISSUE TITLE
What's up with "toggle drawer"?

### ISSUE THREAD

**Issue by godfrey-cw** [maks/MGit#483]
Maybe there's a simpler way to stage/push/pull, if so let me know. But what else would I want to do when I press those three dots except open the drawer to push/pull etc? In other words, why is there a menu with only one button whose only function is to actually open the menu that I wanted to open in the first place?

To be clear, overall I like this app and use it daily. 

While I'm here/speaking of the menu, it would be nice if standard buttons (stage, commit, push and pull) were already exposed, without the need to menu dive.

**Comment by kb-1000** [comment]
That's like that since the upgrade to Android Support... I think I've made a fix for it some time ago but have no idea where it is tbh

**Comment by timmy61109** [comment]
I think it can be operated with instructions, in addition to the existing graphical buttons.

**Comment by godfrey-cw** [comment]
@timmy61109 I'm not sure if I know what you mean by "instructions" as opposed to buttons? Perhaps I haven't spent enough time with the app to know the ins/outs of the interface.

**Comment by kb-1000** [comment]
The solution should be pretty easy, it's just a matter of fixing some layout options. Currently, those options still have the names they had pre-appcompat, but appcompat doesn't recognise those names. The options in the source code have to be renamed, then it'll work as it did before again.

**Comment by timmy61109** [comment]
> @ timmy61109我不確定我是否知道“指令”而不是按鈕的含義？也許我沒有花足夠的時間來了解該應用程序的界面。

The instructions on my side refer to the instructions on Bash. You can add the Bash interface to control Git's actions, not just graphics operations.

**Comment by tanty** [comment]
This is a duplicated of #299

**Comment by godfrey-cw** [comment]
Yes, @tanty you are absolutely right. My mistake, closing in favor of that one.

**Comment by kb-1000** [comment]
Made #494, that should in theory fix it
