### ISSUE TITLE
APK release section stopped being attached

### ISSUE THREAD

**Issue by rancidfrog** [maks/MGit#498]
Why has APK been stopped being attached after https://github.com/maks/MGit/releases/tag/v1.5.2

It is useful for users to try app
And efficient.

**Comment by MalteKiefer** [comment]
Yeah please add it again.

**Comment by maks** [comment]
I stopped doing that as I'd prefer not to distribute stand alone APKs for end user as then they have no way of being notified when a new version is available. 
It also encourages end users to enable side-loading which again in most cases is not something end users should be doing.
For those that don't wish to use Google Play, I believe F-Droid also distributes MGit.
