### ISSUE TITLE
Remove internal editor

### ISSUE THREAD

**Issue by maks** [maks/MGit#504]
There are just too many issues with the internal editor and MGit should really be aiming to work well  and integrate well with external editors rather than trying to be an editor itself, except for commit messages.

**Comment by maks** [comment]
Done in #506

**Comment by kb-1000** [comment]
but why?

**Comment by maks** [comment]
@kb-1000 I documented my reasoning in #506:
> MGit needs to focus on being a good client, not an editor.

MGit needs to focus on providing good git client functionality, not being a text editor, there are plenty of other good open source options for that. Also the existing webview based CodeMirror editor was not providing a good editing experience for users and I wanted to spend my limited time improving git functionality in MGit not text editing.
