### ISSUE TITLE
Can't view files if no text editor is installed

### ISSUE THREAD

**Issue by maks** [maks/MGit#521]
Not having a installed text editor is stopping even viewing files within MGit.

**Comment by edomont77** [comment]
Not sure it's related to this issue, but I've just installed the app on my Xiaomi Mi 9 and I can't see any folders in the path /storage/emulated/0/ when I want to set a custom root storage location for repos.
The same when I want to import (not generate) my SSH key .

**Comment by maks** [comment]
No that's not related, this issue is very specific to how the file viewer inside MGit is invoked. Please file a separate issue for the problem you are experiencing, thanks.
