### ISSUE TITLE
How to clone repos from codeaurora

### ISSUE THREAD

**Issue by wufixx** [maks/MGit#522]

**Comment by maks** [comment]
I'm sorry I don't understand your question, whatever code aura is, you can clone a repo from any service if it provides access via Https or SSH transports.

**Comment by wufixx** [comment]
I mean this repo
https://source.codeaurora.org/quic/la/kernel/msm-4.9

**Comment by maks** [comment]
I'm afraid that is unlikely to work, MGit on an Android device is likely to run out of memory if you try to clone something as big as a linux kernel repo.

**Comment by wufixx** [comment]
No, I just want to clone one tag of them not all

**Comment by kb-1000** [comment]
that doesn't make a difference. MGit doesn't support cloning a single tag, and even if it did support that, it doesn't support shallow clones (as not doing a shallow clone would still download the whole history). In addition to that, JGit seems to do some operations in-memory (in RAM, not on permanent memory), which is the main problem for you probably.
You can verify yourself by just entering the url into the clone dialog, as that's how you'd clone that.

**Comment by maks** [comment]
@wufixx unfortunately MGit [does not yet support shallow clones](https://github.com/maks/MGit/issues/279) which is what is required to clone a remote for only a git ref (ie. a single tag).
