### ISSUE TITLE
Can't see local storage folders when I set the root location

### ISSUE THREAD

**Issue by edomont77** [maks/MGit#531]
Hi. On my Xiaomi Mi 9, when I try to set the root storage location under Settings, I can't see any folder or file in the default /storage/emulated/0 path.
I can just go up in the parent folders.
I double checked the app permissions and the archiving / storage access is allowed.
Can you please check? Do you need more details? Thanks.

**Comment by maks** [comment]
Is your storage on a external SD card?

**Comment by edomont77** [comment]
No, it's the internal device storage.

Il mer 4 mar 2020, 22:39 Maksim Lin <notifications@github.com> ha scritto:

**Comment by maks** [comment]
Thats strange. Quickly testing with on a Pixel 3a running Android 10 and a Nexus 5x running 8.1.0 and using both MGit 1.5.8 and 1.5.7 I have no issues seeing folders and files inside `/storage/emulated/0`

The only thing I can think of is that there is something that Xiaomi have modified in their OS to prevent MGit from accessing that path.

**Comment by maks** [comment]
I should note that I am able to exactly replicate the behaviour you are seeing by going in to System settings -> App permissions and **denying** MGit the storage permission. I would suggest checking that the permission is granted to MGit and that Xiaomi have not modified their variant of Android to have some other way of granting that permission to apps.

**Comment by edomont77** [comment]
Hi maks.
Thank you for your attempts.
I checked again and the archiving permission is granted.
I tried to identify any other related option in the Android settings, but I
can't see anything useful.

Perhaps Mgit depends on sort of Android stock file explorer that Xiaomi
could not have any included in its version of OS?

Regards.


Il mer 4 mar 2020, 23:12 Maksim Lin <notifications@github.com> ha scritto:

**Comment by maks** [comment]
Hmm, sorry I'm not sure what it woucld be then. MGit uses its own custom views for that file browsing so thats not something Xiaomi could change, what you describe is actually the Android OS not returning any file records when MGit is requesting the list of files in that directory.

**Comment by jianjunhuang** [comment]
Hi maks.
I got this issues on my oneplus 6 (Android 10).
But when i downgrade the `targetSdkVersion` to 28,  I can see folder and files in the default /storage/emulated/0 path.
May be some phones use the features of Android Q .
From my point of views, Its'd better to use `MediaStore` instead of `getExternalStorageDirectory`

**Comment by kb-1000** [comment]
Well, migrating is not even nearly as easy as you might think. We're using an old JGit version, and JGit isn't specific to Android, it's for example used by the Git integration in the Eclipse IDE. Of course, I could probably just write a java.nio.file provider, but unfortunately JGit uses a combination of java.nio.file and java.io (which doesn't have this "provider" concept), and java.nio.file was ported to android in Oreo, while this app still supports Lollipop.

**Comment by tbuico** [comment]
I am currently getting this exact issue with my Pixel 3 which is running Android 10 with July 5 2020 security patch. All permissions were given
