### ISSUE TITLE
Add opt in dialog for crash reporting to be compliant with GDPR

### ISSUE THREAD

**Issue by maks** [maks/MGit#533]
[Sub-paragraphs e & f](https://gdpr-info.eu/art-6-gdpr/) would suggest it is not necessary, but in an effort to be as clear as possible with user, a opt in dialog needs to be added to have users agree to crash reporting data be sent.

**Comment by licaon-kter** [comment]
So this was checked with a lawyer? And they said the user either needs to AGREE or GTFO? I was under the impression that "opt-out" of tracking should be an option.

**Comment by kb-1000** [comment]
I wouldn't exactly call this "tracking", it's more like crash reports. But yeah, you cannot review the information sent and agree or disagree like it was possible with the E-Mail solution before, and you cannot use the app without agreeing. I would definitely agree calling that an antifeature, though.
I'm quite sure it wasn't checked with a lawyer.

**Comment by maks** [comment]
@licaon-kter  Per @kb-1000 previous comment, this is *not* analytics tracking, it is for crash and error reporting only, so it will only send anything if and only if a crash or serious error occurs within MGit.

The only purpose for this is for me to be able to know what errors and at what frequency they are occurring for MGit users and to then be able to work on fixing them. I consider this to be the quid pro quo of MGit users using an open src and free piece of software packaged and distributed by me, as I found error reporting via email to be unreliable, unmanagable and not nearly as useful as a dedicated service such as Sentry.

If you are not happy with the current implementation, please raise a *new* issue documenting an alternative implementation, which you can contribute to if you wish.
