### ISSUE TITLE
F-Droid releases seem to have fallen behind

### ISSUE THREAD

**Issue by alerque** [maks/MGit#535]
I found this app on F-Droid and it seems to be the only major open source Android git client, so I jumped in even though it looked like it might be an abandoned project since the last update is over a year ago (1.5.5.1 release Feb 27, 2019). Now having come to the project site I see there are lots more releases and development activity.

What happened to the F-Droid releases?

**Comment by kb-1000** [comment]
I've noticed this too. For MGit, the updates are managed by their bot, and that bot doesn't seem to pick up the new git tags, for whatever reason (idk).
You'll have to create an issue in their metadata repository on GitLab, we can't do anything about that.

**Comment by alerque** [comment]
@kb-1000 You might look at another project I know had issues with this lately: https://github.com/bradyt/cone/issues/61

I'm guessing they have something in place that stops checking for updates once builds start failing, and that it needs poking to get rolling again. Not sure on that though.

**Comment by kb-1000** [comment]
https://f-droid.org/wiki/page/com.manichord.mgit/lastbuild_219
This is... interesting...

**Comment by maks** [comment]
Unfortunately I dont really have any control over how or when F-Droid do their releases of MGit
