### ISSUE TITLE
folder can't be changed - permission issue on Android 10?

### ISSUE THREAD

**Issue by aisbergde** [maks/MGit#542]
**Describe the bug**

set root folder doesn't work, nothing can't be selected. if the current selection will be saved mgit can't be used anymore and needs to be reinstalled.

**To Reproduce**
1. Go to settings, root folder
2. folder is "/storage/emulated0". only ".." is available
3. Click on save
4. previously cloned repositories are not available
5. uninstall
6. reinstall
7. repositories are available again

**Expected behavior**

it should be possible to browse the folder and to select a folder

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: MIUI Global 11.0.8 - Android 10
 - App Version [e.g. 1.5.3]

**Additional context**

 I think this is related to changed permission system in Android 10. Requested rights are not asked.

**Comment by kb-1000** [comment]
Will it require a VFS patched JGit?

**Comment by dev4223** [comment]
Hi there, is there a workaround for this? Because the app is unusable without proper directory browsing. Thanks!

**Comment by aisbergde** [comment]
> Hi there, is there a workaround for this? Because the app is unusable without proper directory browsing. Thanks!

This is also my main issue. Currently I can use mgit only for some testings, how it would work, if the folders would be a common place. But I can't use it for real repositories because it is not possible to access the storage location with some other apps. I can enjoy push and pull and branches and merge (and it looks like it works great), but only with some test repositories.

**Comment by tbuico** [comment]
Seems like the issue might be that mgit has not opted out of scoped storage but also does not utilize it correctly yet.

As a work around until this feature can be merged in, we should make the app opt out of scoped storage.

> If your app hasn't opted out of scoped storage and requests the READ_EXTERNAL_STORAGE permission, users see a different dialog compared to Android 10.
>     -- https://developer.android.com/preview/privacy/storage#permissions-target-any

This is currently the dialog that pops up when installing mgit for the first time on my Pixel 3 which is running Android 10 with July 5 2020 security patch:

![Screenshot_20200719-164403](https://user-images.githubusercontent.com/60446028/87888105-6655a400-c9df-11ea-825b-55bf7e706e81.png)

**Comment by rsteube** [comment]
Yes that works, thanks.
https://github.com/rsteube/MGit/commit/b6fbbbf9a071b6f3aee6de4ac5209a3df01f9d60

**Comment by maks** [comment]
> Yes that works, thanks.
> https://github.com/rsteube/MGit/commit/b6fbbbf9a071b6f3aee6de4ac5209a3df01f9d60

Great. If that works for you, would you like to contribute it as a PR?
