### ISSUE TITLE
Is there any real reason to drop 4.4.4?

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#548]
**Describe the bug**

>This version requires Android 5.0 or newer. 

**To Reproduce**

https://f-droid.org/en/packages/com.manichord.mgit/

**Expected behavior**

>This version requires at least Android 4.1 or maybe even older. 

**Smartphone (please complete the following information):**
 - Device: Any unupgradeable device.
 - OS: Android 4.4.4
 - App Version 1.5.9

**Additional context**
6c232bd591d1f92887872fcb68ea0b8b4d33c5e9

**Comment by kb-1000** [comment]
Yes, there is. This removes the need for bundling Play Services or Conscrypt, because older devices had no support for TLS 1.2.
At least that was the reason maks gave if I recall correctly.

**Comment by KOLANICH** [comment]
The support of the feature from Play Services has been added into MicroG (using Conscrypt). So you can rely on MicroG, it is free and open-source, so is OK for F-Droid.

And, BTW, Conscript usage was introduced in order to support 4.4.4 de-facto unupgradeable devices with rotten openssl (BTW, I have tried to replace openssl with a newly-rebuilt one (triet both openssl from git and boringssl with zero success) , but JNI bindings have refused to tolerate it, the same problems with other shared libs (I have tried on SQLite) passed through via JNI proxy libs (cli tools work when ldpreloaded, java apps failed to initialize), it seems like jni proxy libs are tied to exact chared libs (addresses?) do you have any ideas how to fix it without rebuilding the whole firmware from scratch (the build systems Google has made for building Android are complete shit and are designed to be used by enterprises with own datacenters like Google is, and I feel like it is intentional in order to keep as much developers not from large corporations out of touching walls of Google and its partners' walled garden as possible) ?).

**Comment by maks** [comment]
As per @kb-1000 comment, the main driver was security, but there are also lots of other issues that arise trying to support ancient devices.
The remainder of your latest comment is well off-topic here and is better raised in a different forum.

**Comment by KOLANICH** [comment]
If one has a 4.4.4 device, it doesn't mean he is an idiot who will beleive every bullshit told. Don't tell that dropping support of older devices improves application security anyhow. Supporting 4.4.4 doesn't reduce app security on new devices.

>but there are also lots of other issues that arise trying to support ancient devices.

->

> but there are also lots of other (maybe not yet surfaced) issues that arise trying to develop this app at all

If you want to avoid issues and their solutions and workarounds, then you probably should stop supporting any device in this app at all, because developing is all about issues and solutions to them. No app - no issues related to it. No issues - no app.

**Comment by maks** [comment]
@KOLANICH I welcome civil and respectful conversations and contributions to this project. 

Please refer to the [this projects code of conduct ](https://github.com/maks/MGit/blob/master/CODE_OF_CONDUCT.md) if you are unsure of what is or is not considered acceptable.
