### ISSUE TITLE
Too many issues: add stalebot

### ISSUE THREAD

**Issue by goatandsheep** [maks/MGit#550]
**Is your feature request related to a problem? Please describe.**
There are too many old issues in this repo

**Describe the solution you'd like**
Add stalebot and stalebot config https://github.com/apps/stale

**Describe alternatives you've considered**
Going through all the issues to check for duplicates or wait for info from people who will never respond will be too much work for any maintainer.

**Additional context**

**Comment by maks** [comment]
Thank you for the suggestion, I've recently seen stalebot being used by several other open src projects. However, unfortunately a number of open issues here are both old and still relevant, so I would be very hesitant to just blanket close issue based on their last activity.

**Comment by goatandsheep** [comment]
Okay! No problem 😊 just making a suggestion. Feel free to close this as you see fit
