### ISSUE TITLE
Can't use sdcard as location on some Android devices

### ISSUE THREAD

**Issue by arthuro555** [maks/MGit#553]
**Describe the bug**
You can't use an SD Card as repository, as the default permissions only allow to read not to write.

**To Reproduce**
1. Try to open a local repo from SD Ard and to pull, you will get permission denied for the folder.
2. You can also just try to clone after setting the repositories root to the sdcard

**Expected behavior**
When trying to access the sdcard using the app file picker, it should ask the user to open the sdcard using the system file picker and open the system file picker as write access can only be gained through it.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi 5
 - OS: MIUI based on Android 8
 - App Version: latest version released on the play store the 18 August.

**Additional context**
On some Android phones you need to use the system file picker to gain write access to external storage. See how [this app](https://github.com/deadlyjack/code-editor) handles file system with a custom file picking UI.

**Comment by maks** [comment]
As far as I can tell what you are referring to is using the SAF (storage access framework) which is not workable for MGits requirements.

**Comment by arthuro555** [comment]
Oh. That's a shame 😞 .
