### ISSUE TITLE
move CI to Github Actions

### ISSUE THREAD

**Issue by maks** [maks/MGit#565]
Need to move off Travis CI asap.

Github actions seems a reasonable alternative.

[See here for more context.](https://blog.earthly.dev/migrating-from-travis/)

**Comment by kb-1000** [comment]
That should be reasonably easy to do.
[As seen here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#android), the `ubuntu-20.04` runner has the required SDK components preinstalled.
