### ISSUE TITLE
[chef/chef] WIP: Make habitat cookbook resources client native (#11577)

### ISSUE THREAD

**Issue by luis33338** [maks/MGit#575]
[chef/chef] WIP: Make habitat cookbook resources client native (#11577)

**Comment by luis33338** [comment]
> [chef / chef] WIP: Hacer que los recursos del libro de cocina de hábitat sean nativos del cliente (# 11577)

Forck

**Comment by maks** [comment]
Im sorry I dont think this is related to MGit.
