### ISSUE TITLE
I cant edit files, they are read-only

### ISSUE THREAD

**Issue by EvilCrive** [maks/MGit#577]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maks** [comment]
Thank you for filing this issue, but you will need to provide detailed information per the template as to what you are trying to do, the steps you followed, how you attempted to edit the file, which app you are using to edit the file, etc.

**Comment by EvilCrive** [comment]
ok, i used acode to edit the file.
I tried to change the readme.md to see if i could edit it and commit and push.
And it wouldnt let me save the modifications, saying its read-only.

**Comment by maks** [comment]
Thank you for providing the extra information, that gives me a much better idea of what is happening. I assume this is the ["acode"](https://play.google.com/store/apps/details?id=com.foxdebug.acodefree) editor your are using? 

If so, having a very quick look their open source repo, it seems that it [does not support the Android content provider API](https://github.com/deadlyjack/code-editor/issues/209) which is what is required for text editors to access files when you open them from within MGit.

If you need to open **and** edit files from within MGit, I would suggest [ViperEdit](https://play.google.com/store/apps/details?id=com.manichord.viperedit) which is an open source editor that I republished last year for exactly this reason. More historical information can be found in #525. If you would prefer to use a different editor NMM is another option that I have been told also supports content providers for file editing.
