### ISSUE TITLE
Question: does MGit support Access Tokens and how do I use them?

### ISSUE THREAD

**Issue by steffomix** [maks/MGit#579]
Just got a deprecation warning from GitHub that I need to use tokens to access and update my code. So now I wonder how to use them with MGit?

Even not knowing how to use or if it works I just added a token in my git config under the [name] section like this:
[name]
  name = <my_name>
  email = <my_email>
  token = <my_token>

With regards
Stefan

**Comment by maks** [comment]
It's quite possible to use GitHub personal tokens, please see: https://github.com/maks/MGit/issues/559#issuecomment-871266771
