### ISSUE TITLE
hey is this repo dead

### ISSUE THREAD

**Issue by sunilroyy007** [maks/MGit#583]
i seen more than 10 months and no update. i just came to know about this app. can you clarify when is next update will come or is repo unmaintained.

**Comment by maks** [comment]
No this repo is not "dead" as you can see by looking at the issues here sorted by "recenty updated".

If you are asking if there is active development going on, the answer is no. I have not been dedicating time to working on this codebase over the last couple of years BUT that does not mean it is not being "maintained" as I respond to issues as promptly as I can and am **very** happy to receive, review and accept contributions and do releases based on those when I have the time and think it makes sense do so.
