### ISSUE TITLE
Strezless Musick needs Metadata resources from an open source

### ISSUE THREAD

**Issue by StrezlessMusick** [maks/MGit#585]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [trying to customize and manage my metadata, especially for my creative works]

**Describe the solution you'd like**
Find a way to list, manage, and execute all my creative works in an clear and organized manner that's not so complex and easy to understand in a organized open source software. Not allot of money til my royalties multiply,

**Describe alternatives you've considered**
I've been looking into data management softwares such as Wavo but don't want to subscribe to monthly fees as of now due to my unstable income and residence cause there is no telling how long it will take til I move elsewhere. Been like this since I was 14 still.

**Additional context**
Working on copyrights with my local gov office and new releases as I work on a book titled "It's a Cold Wide World" to release for a future film I want to direct if possible so help me God. It will be based on the real life story of Sin Estres from Strezless Musick so be on the lookout. Also wanna thank anyone who has been supporting this project from the very beginning because without you I feel like it's not possible nor worth the time investing in such activity, thank you.
  
Omar Dejesu Orrantia
BMI Affiliate
Strezless Musick Productionz
Featuring Sin Estres

![Uploading u2{9551934} (6ceef828-c6a5-44c4-99b7-08b1b2af7a4b id=0x7f0a037e) …](Sin Estres)

[]()

**Comment by maks** [comment]
I'm sorry but this has nothing to do with MGit.
