### ISSUE TITLE
Private Repository clone failes every time

### ISSUE THREAD

**Issue by RexZetronYT23** [maks/MGit#586]
**Describe the bug**
If i try to import my private repository from github it fails, "not authorized". My credentials are right.

**To Reproduce**
Try to clone a private repo from a organization.

**Expected behavior**
A cloned repo

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 9A
 - OS: Android 10
 - App Version: 1.5.10

**Comment by maks** [comment]
Are you using Github with a username/password auth?

If you are, then please see: #559 as Github have stopped allowing it and you will need to switch to an alternative such as using a personal auth token.

**Comment by RexZetronYT23** [comment]
yes i was using my password. I already found the way to use a PAT.
