### ISSUE TITLE
RSA key with SHA-1 no longer alllowed.

### ISSUE THREAD

**Issue by xingangshi** [maks/MGit#601]
git@github.com:username/repo_name.git: 

*ERROR*: You're using an RSA key with SHA-1 which is no longer allowed. Please use a newer client or a different key type.

Please see https://github.blog/2021-09-01-improving-git-protocol-security-github for more information.

**Comment by PyCoder040** [comment]
This is a well known issue with GitHub.  I can confirm that MGit works just fine with GitHub using HTTPS access and a personal token.

**Comment by maks** [comment]
Yes I'll need to look into it, it will be due to [Jsch](http://www.jcraft.com/jsch/) the underlying ssh library that MGit uses for ssh implementation.

**Comment by xingangshi** [comment]
> This is a well known issue with GitHub. I can confirm that MGit 1.5.10 works just fine with GitHub using HTTPS access and a personal token. Using it right now as a matter of fact. ;)

thanks, i will try this way. but now i just use MGit to manage the codes and push to github by [termux](https://termux.com/)

**Comment by ilippert** [comment]
> Yes I'll need to look into it, it will be due to [Jsch](http://www.jcraft.com/jsch/) the underlying ssh library that MGit uses for ssh implementation.
I allow myself to point to a post that might be of interest with respect to Jsch - https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/

**Comment by maks** [comment]
@ilippert thanks for posting the link, I'll look into that new fork of Jsch and see if I can make use of it for MGit.

**Comment by ilippert** [comment]
great, thank you so much for the closure of the issue! I look very much forward to the next release and advertise it to my students who use git.

**Comment by maks** [comment]
I'm going to reopen this issue as while @kb-1000 did a great job with adding support for using ED25519 keys with in PR #609 testing it on a Pixel 4a running Android 12 shows me its not possible to browse and see a externally created private key to import it into MGit unless it has a extension of a media file, eg. `.png`, `.mp3 `.wav`, etc. The extension of course doesn't matter to MGit, so this is a work around for now just to name the ssh private key with that extension to import it, but this is not very user friendly so will need a better solution.

**Comment by kb-1000** [comment]
That seems like a different, only loosely related issue.
Could that be related to the storage security changes in more recent versions?
If so, it might be necessary to use the OS' file picker here.

**Comment by maks** [comment]
@kb-1000 yes I think thats likely to be the case. And that's a good point, I'll open a separate issue for the file dialog problem.

For those on this thread who would like to test out the new support for ED25519 keys, the 1.6.2 release is now rolling out to the Beta testing channel, so if you would like to try it out, just please select to be a Beta Tester when you look at MGit's listing on Google Play.

**Comment by ilippert** [comment]
> @kb-1000 yes I think thats likely to be the case. And that's a good point, I'll open a separate issue for the file dialog problem.
> 
> For those on this thread who would like to test out the new support for ED25519 keys, the 1.6.2 release is now rolling out to the Beta testing channel, so if you would like to try it out, just please select to be a Beta Tester when you look at MGit's listing on Google Play.

I shall wait for it being on f-droid, or an apk directly downloadable ;) then I am very happy to test.

**Comment by kb-1000** [comment]
What I'd also like to note is that the JSCH update didn't just add ed25519 support, regular RSA keys will also work again.
As far as I understood (correct me if I'm wrong) the SHA1 hash was part of the key exchange algorithm, not the key itself. The newer JSCH version then implements the newer and more secure algorithms.
However I only tested with a newly generated RSA key, not an old one.

**Comment by maks** [comment]
Thats a great point @kb-1000, I had missed that it should be possible to use RSA keys with the updated version of JSCH and infact I just tested creating a RSA key (4096 length) in MGit and using the new RSA key with the 1.6.2 release and it works fine with Github.

**Comment by maks** [comment]
Just to let everyone know the new release with the SSH key fix is now available on Google Play.

For those using F-Droid, I have created a tag for the release but I have no other involvement with when it may be released by them.

**Comment by ilippert** [comment]
> For those using F-Droid, I have created a tag for the release but I have no other involvement with when it may be released by them.
I have notified the F-droid - as I was not sure whether their algorithm automatically picks up the new release. https://gitlab.com/fdroid/fdroiddata/-/issues/2634
