### ISSUE TITLE
Show git version in settings

### ISSUE THREAD

**Issue by niccokunzmann** [maks/MGit#606]
**Is your feature request related to a problem? Please describe.**
I was looking for the git version to compare the different git installations on the phone.

**Describe the solution you'd like**
I would like to know which version of git this software is shipped with.

**Describe alternatives you've considered**
I do not know - I could not find out. maybe a hook that puts the version into the file.

**Additional context**
I was troubleshooting as the git version from the userland linux installation creates invalid repositories - the hashing does not work.
This app however does the right thing. So, I wondered if the git version might be too old.

**Comment by kb-1000** [comment]
MGit doesn't use Git at all... it uses JGit, a Git reimplementation written in Java.
Currently, it's using JGit 3.7.1 from 2015, as seen here:

https://github.com/maks/MGit/blob/3fef93ccac48da5985f62d7e90fe83e6ac5c7e96/app/build.gradle#L90
