### ISSUE TITLE
Import ssh key file browser on Android 12 only shows some file types

### ISSUE THREAD

**Issue by maks** [maks/MGit#610]
Following on from #601 the current "import key" MGit's file browser UI on Android 12 (possibly other recent versions too)  seems to only display files with known media extensions, eg. `mp3`, `png`, `wav`, etc. Which makes it harder than it needs to be to import a ssh private key into MGit.

This is likely due to security restrictions, so probably need to switch to using a standard Android File browser/selection api.

**Comment by EverThingy** [comment]
I can confirm that this issue is also present on Android 11. (OnePlus Nord running Oxygen OS).

**Comment by ilippert** [comment]
I suggest, for the meantime, you reference this issue at https://github.com/maks/MGit/wiki/UserManual#private-key-authentication - because otherwise users might be confused (that is, until they find this issue)

**Comment by maks** [comment]
Fixed by #616
