### ISSUE TITLE
How to clone repo from Github

### ISSUE THREAD

**Issue by leoweyr** [maks/MGit#614]
When I tried cloning my repo from Github in MGit step by step, and then it needed me to input something as picture:
![IMG_20220328_091905](https://user-images.githubusercontent.com/58080150/160310850-92974d40-c647-4aa5-bdc7-fe6f2314a628.jpg)
![IMG_20220328_091914](https://user-images.githubusercontent.com/58080150/160310856-8670e939-3a75-4685-8731-ac509bfd8aab.jpg)

I inputted username and password of my Github correctly, but it was still error. 
![IMG_20220328_091923](https://user-images.githubusercontent.com/58080150/160311362-89d95cab-4244-42ee-aab5-3f4a7c6c2837.jpg)

I had tried getting a solution in MGit repo and MGit Wiki, I lost, so I need help in this issue.

**Comment by maks** [comment]
Thank you for reporting the issue.

When using HTTPS with Githuhb, you need to use a Personal Auth Token as your password, not your actual Github account password.  You can get [much more information about how to create a personal token from Github's documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

**Comment by TianJinRong** [comment]
> Thank you for reporting the issue.
> 
> When using HTTPS with Githuhb, you need to use a Personal Auth Token as your password, not your actual Github account password. You can get [much more information about how to create a personal token from Github's documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

I think it would be greate to post this guidline to README at the project.
