### ISSUE TITLE
Unable to use github

### ISSUE THREAD

**Issue by niccokunzmann** [maks/MGit#618]
**Describe the bug**

Whenever I want to push to github, I get an error message telling me that I cannot use an RSA sha128 bit key.

**To Reproduce**
1. Create an RSA key
2. try to clone from github using ssh

**Expected behavior**

I would like to create a key with mgit AND use it with github.

**Screenshots**

![Screenshot_20220405-221728](https://user-images.githubusercontent.com/564768/161842588-88cbc2da-74ab-4af4-b110-e4ee17404010.png)

**Smartphone:**
 - Device: Moto
 - OS: Android 6
 - App Version 1.5.10

**Additional context**

Github disables dsa and rsa sha 128 it keys
https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by l3laze** [comment]
Using a personal access token (with "repo" scope) as the password when logging in through the app (e.g. when pushing) is working for me currently.

**Comment by Gr-Nobel** [comment]
Yes just create a personal access token (generated from gitHub)

**Comment by Qinggao1729** [comment]
For future reader: you may want to use "Token(Classic)" instead of "Fine-grained token (Beta)".
