### ISSUE TITLE
gitlab issues, can't add new repositories and can't push and pull some existing

### ISSUE THREAD

**Issue by aisbergde** [maks/MGit#619]
**Describe the bug**
In the past MGit worked fine with my gitlab repositories (using https)
The links which are opened on "Open remote url" works fine (I need to login because these are privat repositories)

Currently I can pull and push only one (1) repository in MGit. For other repositories I get errors. I don't know what could be the difference between these repositories.

```
ERROR occurred
Clone failed
Operation not permitted
```

Sometimes I get other errors, for example:

```
Push Result
[refs/heads/main] Remote ref update was rejected.
```

Or when I try to force pull, I get

```
Pull failed
Error occurred
Exception caught during execution of reset command. {0}
```

I also can't add new gitlab repositories. I get the same error

```
ERROR occurred
Clone failed
Operation not permitted
```

Some credentials are stored anywhere in MGit.  But I did not change my credentials. In the past when I added a new repository I got some requests about credentials, but I can't find how to force MGit to refresh or to reconnect.

**To Reproduce**
1. try to clone a valid repository addres
2. See error

**Expected behavior**
I want to be able to clone gitlab repositories again

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: Android 11
 - App Version 1.6.2

**Additional context**

**Comment by aisbergde** [comment]
the issue is related to version 1.6.1 (f-droid) 
I deinstalled and reinstalled and it doesn't work, no credentials are asked
Then I deinstalled 1.6.1 again and installed 1.5.10 (f-droid) and it worked again.

Now credentials are asked several times (when adding a repository and when doing the first operation). But this was also the case before.

**Comment by Jacobax** [comment]
same here. cant clone any repository
v1.6.1 from f-droid, android 12

**Comment by imshenwei** [comment]
Same Proplems:
Error: operation not permitted
Now works correctly by setting the root storage location _**ONLY**_ to /storage/emulated/0/Documents!!

Device: Redmi K30 PRO Zoom Edition
OS: Android 11
App Version 1.6.1

**Comment by federovsky** [comment]
I had a similar problem, but when tried to clone from bitbucket, after changing the default root storage location.
I got this:
```
ERROR occurred
Clone failed
Operation not permitted
```
Following the posts here, I tried to set it to /storage/emulated/0/Documents and it works.
Device: OnePlus 8T
OS: Android 12
App Version 1.6.2

**Comment by maks** [comment]
These all appear to be due to the Android 11+ permissions issue, even though this is was opened first, I'm going consolidate tracking this in #620.
