### ISSUE TITLE
Infalter error

### ISSUE THREAD

**Issue by Moon-Mind** [maks/MGit#637]
**Describe the bug**
While trying to clone a privat repo with Name and personal access token 

**Screenshots**
![Screenshot_20220517-104435](https://user-images.githubusercontent.com/52799853/168770008-daba3b36-890c-4c4d-8535-27cdb43bdab9.png)

**Comment by maks** [comment]
Thank you for opening this issue.
Is this a large git repo? As I have seen this error caused in the past when JGit (the Git library that MGit uses) runs out of memory, as it needs to load the whole contents of the Git repository while cloning. Eg. long running projects with years of history, often have hundreds of MB or more of commits and objects in their Git repo history.

**Comment by Moon-Mind** [comment]
yes its a large repo

**Comment by maks** [comment]
unfortunately this is a known issue with large repositories, please see: #54
