### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by hgau1** [maks/MGit#649]
Hallo,
seitdem ich ein eigenes Verzeichnis für MGit-root ausgewählt habe, funktioniert weder Clonen noch das Anlegen eines neuen lokalen Repositories. Ich erhalte die Meldung "Operation not permitted". MGit hat auf meinem Galaxy Tab 7 auch nur die Berechtigung auf Mediendateien zuzugreifen. Ich habe aber auch keine Möglichkeit, mehr zuzulassen. 

Auch nach einer Neuinstallation ändert sich nichts. 

Gruß Heiko

**Comment by TusGrid** [comment]
have the same question

**Comment by maks** [comment]
@hgau1 Are you using Android 11 or newer?

**Comment by hgau1** [comment]
I use Android 12.
But I read about the reason in an other thread. After this I installed MGit over F-Droid. Since there it works fine.

**Comment by maks** [comment]
@hgau1 Glad to hear its working for you now. Yes for now sadly the only way to get it working on Android 11+ devices is to use the new version from F-Droid.
