### ISSUE TITLE
Crash when Setting Root Storage location for Repos

### ISSUE THREAD

**Issue by vorburger** [maks/MGit#658]
**Describe the bug**
Boum, crash, when Setting Root Storage location for Repos.

There's a dialog to submit an error report.

**To Reproduce**
1. Go to Settings
2. Click on _Setting Root Storage location_

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - App Version: 1.6.2

**Additional context**
Do you want a stacktrace?

Or a PR with a fix? 🤗

**Comment by maks** [comment]
@vorburger thank you for reporting this, but given you are on Android 13 this will be yet another aspect of #620.
