### ISSUE TITLE
clone a repository with private key

### ISSUE THREAD

**Issue by maks** [maks/MGit#66]
_From @alex29ua on March 15, 2014 8:10_

I have a repository access which requires a private key instead of password (password-protected key is what I have).
I've added my key to SGit, but I don't see how to use it further. 
Is there such an option?

_Copied from original issue: sheimi/SGit#60_

**Comment by maks** [comment]
_From @sheimi on March 15, 2014 9:13_

Now, the private key with passphrase has not been supported.

**Comment by maks** [comment]
_From @swus13 on April 1, 2014 2:54_

Can you at this as an feature request? All my repos are only  acessable by pasword protected keyfiles.

Thanks a lot

**Comment by maks** [comment]
_From @rosenstrauch on June 1, 2014 18:29_

should it work with passphraseless keys?

**Comment by maks** [comment]
_From @mikofski on September 22, 2014 17:39_

@sheimi I think implementing passphrase shouldn't be too hard, have a look at ...
https://github.com/mikofski/JGit4MATLAB/blob/master/%40JGit/UserInfoSshSessionFactory/src/com/mikofski/jgit4matlab/UserInfoSshSessionFactory.java
(I followed this [SO answer](http://stackoverflow.com/a/7955937/1020470))
I think you could replace or refactor parts of ...
https://github.com/sheimi/SGit/blob/master/SGit/src/me/sheimi/sgit/ssh/SGitSessionFactory.java
with the `UserInfoSshSessionFactory`
then  in ...
https://github.com/sheimi/SGit/blob/master/SGit/src/me/sheimi/sgit/activities/explorer/PrivateKeyManageActivity.java
you could also copy the passphrase in the file `.jsch-userinfo` to the internal memory. You could do this without dialogs, but then the user would be required to store the passphrase initially in `.jsch-userinfo` which would presumably be in the same folder they pointed to for the private key.

**Comment by maks** [comment]
_From @cboettig on November 22, 2014 5:46_

+1 support for password protected private keys would be great.

**Comment by maks** [comment]
_From @waynespace on August 26, 2015 1:1_

I'm a fresh .so where to find my private key ?

**Comment by maks** [comment]
_From @fmherschel on September 1, 2015 18:10_

I also miss the option or action to 'combine' a private key with a git remote repoitory. 

Now I have a git repository cloned but needed to temporary set a password I could type-in at the android and than closed the account again for pwd login.

I imported a private key (txt) file and can see it in the SGit App. My private key for this purpose does not have a password (which is not secure).

But still SGit asks for username/password.

How to "combine" the private key to the Git repository, so it gets used?

Is the a naming scheme for private keys?

**Comment by maks** [comment]
_From @mlarcher on September 4, 2015 21:12_

The app looks great, but really lacks that passphrase feature on private keys. Are you planning on implementing it or is there some technical difficulties that represent too much of a challenge ?

**Comment by maks** [comment]
_From @Lrs121 on September 5, 2015 0:12_

These should help. This is how I clone projects and manage my keys. Sorry if this is long.

![screenshot_2015-09-04-16-59-23](https://cloud.githubusercontent.com/assets/3093776/9696614/0cfa16e4-5328-11e5-8a8a-6dd144b7e446.png)
![screenshot_2015-09-04-16-59-31](https://cloud.githubusercontent.com/assets/3093776/9696612/0cf6af0e-5328-11e5-82cd-d2b5e9a1b52b.png)
![screenshot_2015-09-04-17-04-44](https://cloud.githubusercontent.com/assets/3093776/9696613/0cf78226-5328-11e5-950c-effee039fd40.png)
![screenshot_2015-09-04-17-07-03](https://cloud.githubusercontent.com/assets/3093776/9696615/0cfc4824-5328-11e5-8981-50027886a62f.png)

**Comment by maks** [comment]
_From @fmherschel on September 11, 2015 10:51_

Hmm I tried it that way, but it does not work for me. But I did not created the private/public key pair in putty. So which private/public key formats does SGit support? 
- Keys created with gpg?
- Keys created with ssh-keygen?
- Keys created with putty (f.e ppk)
- Others?

**Comment by maks** [comment]
_From @Lrs121 on September 11, 2015 21:20_

My key wasn't made with putty either, it was generated with Linux. however I use filezilla as a portable app and that doesn't support keys with a passphrase either. so filezilla stripped the pass phrase for me and that's what I use.

**Comment by maks** [comment]
_From @endosynth on August 19, 2016 13:16_

+1 support for password protected private keys would be great.

note that my putty-generated private key without a password worked fine on an Android tablet, Samsung Tab4

**Comment by maks** [comment]
I am working on this for the next release.
Please note that due to the requirement to securely store the private key passwords, this feature will only be available on devices running API 18 (JB 4.3) and higher.

**Comment by maks** [comment]
Just a final comment - this will ship in the next release (1.5.2) and will be available shortly in [Google Play Beta version of MGit](https://play.google.com/apps/testing/com.manichord.mgit) as will start makign beta releases available prior to making a new release available in Play.

**Comment by polyzen** [comment]
Will the beta also be on F-Droid?

**Comment by maks** [comment]
@polyzen unfortuntately no.
I do not control or have access to F-Droids distribution of MGit apks. Also afaik F-Droid does not have a mechanism for distributing alpha/beta versions of an app.
I would assume though that eventually this new version (1.5.2) will make it into F-Droid.
If you can't or prefer not to use Google Play and would like to test the new release, the apk is available here in the release on [Github](https://github.com/maks/MGit/releases/tag/v1.5.2) though it will make you uninstall the F-Droid provided version as F-Droid signs the apk themselves with their own keys.
If you do do that (I would greatly appreciate any testing people can do) then **please be careful** you do not have any outstanding local changes or commits in your MGit managed repositories if they are *not* stored in a location that all apps can access (eg.  `/storage/sdcard` ) so that you can then import them again after you install the new version of MGit.

**Comment by maks** [comment]
[also initial documentation for this new feature has been added to the user manual](https://github.com/maks/MGit/wiki/UserManual#private-key-authentication)

**Comment by polyzen** [comment]
The maintainer has [committed the latest releases](https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.manichord.mgit.txt). 🎉

A note from him:
"fdroid does not check the github label, but the actual tag name and the android specific version information, so as far as fdroid is concerend, this is not a pre-release."

**Comment by maks** [comment]
@polyzen great! And thanks for letting me know and also good to know about how F-Droid's releases work too.
