### ISSUE TITLE
[Question] How to create a public key ?

### ISSUE THREAD

**Issue by KaKi87** [maks/MGit#693]
Hello,

I found the "ssh keys" item in settings, but it seems to only generate a private key.

So, how to generate a public key, that I can import from my account ?

Thanks

**Comment by Feelcame** [comment]
Its generate a both private and public keys at same time

**Comment by KaKi87** [comment]
Where ?

**Comment by Feelcame** [comment]
> Where ?

Long click on the file → Three dots menu → Show public/private key

**Comment by Feelcame** [comment]
![Screenshot_20230807-161200_MGit](https://github.com/maks/MGit/assets/17731587/547180e8-b466-44ab-9f4c-9b8e6c7fa333)

**Comment by KaKi87** [comment]
Oh, I see.

This is very confusing, because on desktop `git`, the public key file has a name ending with `.pub` while the private key file next to it hasn't, that's how you know what's what.

Thanks
