### ISSUE TITLE
Enhance the description or the activated feature of mgit

### ISSUE THREAD

**Issue by jpggithub** [maks/MGit#705]
On f-droid (https://f-droid.org/en/packages/com.manichord.mgit/), the description of Mgit indicates that
```
Antifeatures:
* Tracking: You can't run the app unless you agree to send error and
crash reports to the developers Sentry.io account. The reports will contain
information about the device you are using, a unique randomly generated ID
and potentially some metadata about the git repo that you are using. 
```
This description is not reassuring at all.

Perhaps you can explain what "potentially" means, simply deactivate the reports, or give the ability to the user to de/activate the reports ?

**Comment by maks** [comment]
That is out of date, as you can see, Sentry usage was removed almost 2 years ago: https://github.com/maks/MGit/pull/597

I don't know why FDroid have not updated the description.

**Comment by jpggithub** [comment]
Thank you for your answer. I will see what can be done with f-droid and I will post the result here for your information.

**Comment by licaon-kter** [comment]
@maks 
> I don't know why FDroid have not updated the description.

Because no one opened an issue or a MR or anything :shrug: 

/LE: done in https://gitlab.com/fdroid/fdroiddata/-/commit/3628f774cfffa0066b1ae607672ba68d34299ea4

**Comment by jpggithub** [comment]
Thanks to both of you!

**Comment by jpggithub** [comment]
FYI, the metadata were updated correctly

**Comment by maks** [comment]
thanks @licaon-kter for getting that done, much appreciated! 👍🏻
