### ISSUE TITLE
Implement 2FA of GitHub

### ISSUE THREAD

**Issue by modelrailroader** [maks/MGit#709]
This GitHub-Client for Android is a nice idea but I activated 2FA for logging into GitHub and your client does not support this.
When cloning a repo and entering my credentials, an error occurs that says I'm not authorized to clone that repo.

**Comment by maks** [comment]
Thank you for opening this issue, but MGit is a Git client **not** a GitHub client.

To use MGit with GitHub's 2FA you can either [use SSH](https://github.com/maks/MGit/wiki/UserManual#ssh) or use [a personal auth token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)
