### ISSUE TITLE
Doesn't update files when created by another application 

### ISSUE THREAD

**Issue by CodeMazeSolver** [maks/MGit#712]
MGit does not notice new files created by another application in the folder structure of the repository.

In the particular case I'm using Obsidian to create a new markdown file.
Changes in existing files are tracked. However, the additional markdown file, which can also be found by the system file explorer, does not show up in MGit. Thus, git cannot track any changes made and commits are empty.

**Comment by isikyus** [comment]
Is this the same issue as https://github.com/maks/MGit/issues/620 ?

**Comment by CodeMazeSolver** [comment]
Yes, you're right
