### ISSUE TITLE
Not compatible with Galaxy Note 10.1

### ISSUE THREAD

**Issue by FabianInostroza** [maks/MGit#72]
Tried to install from playstore and it says that is not compatible with my device (running android 4.1.2)

**Comment by Lrs121** [comment]
The reason can be found right (
[here](https://github.com/maks/MGit/blob/master/build.gradle#L22)

SDK version 18 only supports Android 4.3 and newer.

**Comment by maks** [comment]
Yes I up'd a fair bit the minimum version compared to what the last release of SGIt had (which was SDK >14).
I'm not going to go back that far with MGit but it should be possible to do >16, which will cover down to 4.1.X

**Comment by maks** [comment]
Fixed in b7859323fc9908ac65f7e16b52a2d28d6915597f
This will shortly be published on Google Play as version 1.5.0

**Comment by FabianInostroza** [comment]
Thanks!
