### ISSUE TITLE
Can the JGit dependency be upgraded?

### ISSUE THREAD

**Issue by Zacharia2** [maks/MGit#721]
The current latest version of JGit is 7.0.0. The version that the project depends on was released in 2015, which is too old.

**Comment by Zacharia2** [comment]
https://projects.eclipse.org/projects/technology.jgit/governance

https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit

**Comment by maks** [comment]
Unfortunately that's not possible due to newer versions of JGit requiring newer versions of Java than is supported on older versions of Android so would mean dropping support for those older versions of Android, please see #26  for more details.
