### ISSUE TITLE
Hello me😭

### ISSUE THREAD

**Issue by basanzietech** [maks/MGit#723]
![Screenshot_20240919-070236](https://github.com/user-attachments/assets/14267339-4794-4c04-b38c-a2c2de6a5288)

**Comment by maks** [comment]
Given this is Github, please refer to the [user manual regarding support methods of authentication](https://github.com/maks/MGit/wiki/UserManual#authentication).

**Comment by basanzietech** [comment]
![Screenshot_20240924-190605](https://github.com/user-attachments/assets/b4a29549-0666-4805-8f65-4f15d5b449b2)
![Screenshot_20240924-190615](https://github.com/user-attachments/assets/35e6118c-6eb7-4ee9-b151-f5232f66b819)
![Screenshot_20240924-190647](https://github.com/user-attachments/assets/a1ca82f0-8287-4a8e-951a-89aba1aa78ef)

**Comment by maks** [comment]
Posting only screenshots is not helpful. 
Can you please provide details of what you used for the password and how you created the token?
