### ISSUE TITLE
No longer supported?

### ISSUE THREAD

**Issue by SpectureCarrier** [maks/MGit#724]
Is this software no longer being maintained?

**Comment by maks** [comment]
This is a very old codebase and git clients in general seem to not be on Google Plays allowed list of apps that will be granted "All Files" access permission, so the future of this or any other app on Google Play seems uncertain.

In the meantime I am slowly working a complete rewrite of MGit, but even an early beta of that is still quite a while off.
So MGit is currently maintained in that any serious issues such as security issues will be addressed but there is no active development of new features in this codebase.

**Comment by farfromrefug** [comment]
@maks I am very interested in contributing  as I will really need this app to maintain all my OSS projects while on a trip next year.
Is your rework already on github ? Would like to help

**Comment by maks** [comment]
@farfromrefug thanks for letting me know. I've got a few different experimental branches that I need to clean up and then I'll push them up here when I get a some time and let you know.

**Comment by farfromrefug** [comment]
@maks btw just because i handled that in my app. MGit should use `MANAGE_EXTERNAL_STORAGE` that way we can read/write anywhere on the phone using `java.io.File` and thus `jgit`
