### ISSUE TITLE
Can't login into account secured with 2-factor auth

### ISSUE THREAD

**Issue by mmethot** [maks/MGit#76]
It would be nice to have the ability to actually log in with a multi factor authenticated account. Otherwise, I will never be able to use this application at all.

Thanks.

**Comment by maks** [comment]
If you are using 2FA on Github you will need to use a Personal Authentication Token as your password, please see the Github docs for [more details on how to generate a token](https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password).

**Comment by jancborchardt** [comment]
It would be a nice enhancement to have that notice in the Auth error popup, and linked to https://github.com/settings/tokens :)

**Comment by maks** [comment]
@jancborchardt yes that would be helpful but I don't see how that will be possible as service providers like Github and Bitbucket do not return specific error states/codes for this condition.

**Comment by jancborchardt** [comment]
@maks maybe a good quick fix would be to simpl add a »Using 2FA?« button to the error popup when trying to auth with Github. That could open a small note saying you need to generate a token, and linking to the »how to generate a token« page.
