### ISSUE TITLE
src/main/res/values-zh-rCN/arrays.xml

### ISSUE THREAD

**Issue by yuxue0927** [maks/MGit#77]
<string-array name="repo_operation_names">
        <item>新的分支</item>
        <item>拉取</item>
        <item>推送</item>
        <item>添加到暂存区</item>
        <item>提交</item>
        <item>重置</item>
        <item>合并</item>
        <item>Fetch</item>
        <item>改变基点</item>
        <item>择取</item>
        <item>比较</item>
        <item>新建文件</item>
        <item>新建文件夹</item>
        <item>远程</item>
        <item>Remove Remote</item>
        <item>删除</item>
        <item>Config</item>
    </string-array>
这里导致菜单错位

**Comment by maks** [comment]
Thank you very much for reporting this and providing a fix!
This fix will go into the next release.
