### ISSUE TITLE
Broken menu in repository

### ISSUE THREAD

**Issue by spainer** [maks/MGit#85]
The menu in the repository view is broken. The items up to "Merge" are okay, but everything from "Rebase" seems to be "Fetch" (which is not included in the menu) and from Cherry Pick on all items behave like the item above. It seems that a "Fetch" item is missing after merge, but the positions are used for identifying the selected item. I am using German translations, perhaps this is a problem.

**Comment by spainer** [comment]
Looking at the file `MGit/src/main/res/values-de/arrays.xml` and comparing it to `MGit/src/main/values/arrays.xml` I saw that indeed the string for Fetch is missing and that the German translation has one item too few.

**Comment by maks** [comment]
Thanks you very much for reporting this and submitting a PR too!
