### ISSUE TITLE
Ability to view repos without moving

### ISSUE THREAD

**Issue by MaximumPotato** [maks/MGit#90]
I have several Repos I'd like to store in different locations. MGit only allows you to view repos stored in the root storage location you have set in settings, and anything you attempt to import from outside of this location is cloned there before you can view it. Would it not make sense to be able to view repos from anywhere in storage?

**Comment by maks** [comment]
You can choose to import a repo "in place" and then MGit will **not** copy it into its root storage location for repos. Please see the manual entry for a little details: https://github.com/maks/MGit/wiki/UserManual#importing-a-local-repo

**Comment by MaximumPotato** [comment]
I somehow missed that completely when looking through the documentation earlier. That mostly solves the problem. Is it possible to clone directly to a specified location as well?

**Comment by maks** [comment]
No worries, the manual is very new and I haven't yet had a chance to link to it in the readme and play store listing.

And no, unfortunately there is no way to clone into a different directory from the root one set in the settings.

**Comment by MaximumPotato** [comment]
Alrighty, that's good to know at least. I might open an issue/request for the cloning to a specific directory feature, but right now moving things manually and importing as external works fine. You've answered everything I was wondering so I'll close this one. Thanks!
