### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by grauschnabel** [maks/MGit#91]
Short: How can I edit typescript files?

**Comment by maks** [comment]
You should be able to select the typescript file by pressing on it to view it and then once viewing it press on the pencil icon in the top right hand corner to begin editing.
If it doesn't work as above, please let me know what happens (include screenshots if possible), any error messages or dialogs you see, etc.

**Comment by grauschnabel** [comment]
It just asks me for an app to view the file, in German in my case, but doesn't show the content. Html, json, is, rb, scss works fine, just .ts file asks for an app but doesn't find any...

**Comment by maks** [comment]
Thanks that gives me a better idea of what it happening and will look into in further.

**Comment by kaeptmblaubaer1000** [comment]
@maks it tries to start a video player.

**Comment by maks** [comment]
@kaeptmblaubaer1000 I'd expect that's because `.ts` files were used for used for mpeg2/4 files. 
I think the issue is how MGit determines a files mimetype using `android.webkit.MimeTypeMap`
Would be nice to perhaps find a better mimetype mapping lib for this purpose.
